= skupper token create

Create a token.
The 'link create' command uses the token to establish a link from a remote Skupper site.

.Synopsis

Create a token.
The 'link create' command uses the token to establish a link from a remote Skupper site.


 skupper token create <output-token-file>  --[option]



.Options


expiry:: 
Expiration time for claim (only valid if --token-type=claim) (default 15m0s)
 (duration)
// 
name:: 
Provide a specific identity as which connecting skupper installation will be authenticated (default "skupper")
 (string)
  -p, --password string     A password for the claim (only valid if --token-type=claim). If not specified one will be generated.
  -t, --token-type string   Type of token to create. Valid options are 'claim' or 'cert' (default "claim")
uses:: 
Number of uses for which claim will be valid (only valid if --token-type=claim) (default 1)
 (int)


.Options inherited from parent commands


// 
// 
// 


.See also

* xref:skupper_token.adoc[skupper token]	 - Manage skupper tokens


// = Auto generated by spf13/cobra on 6-Oct-2022
