= Skupper init

Initialise skupper installation

.Synopsis

Setup a router and other supporting objects to provide a functional skupper

installation that can then be connected to other skupper installations

`skupper init [flags]`

.Options

* `site-name - string`                       Provide a specific name for this skupper installation
* `enable-console`                         Enable skupper console (default true)
* `create-network-policy`                  Create network policy to restrict access to skupper services exposed through this site to current pods in namespace
* `console-auth - string`                    Authentication mode for console(s).
One of: 'openshift', 'internal', 'unsecured'
* `console-user - string`                    Skupper console user.
Valid only when --console-auth=internal
* `console-password - string`                Skupper console user.
Valid only when --console-auth=internal
* `ingress - string`                         Setup Skupper ingress to one of: `[route|loadbalancer|nodeport|nginx-ingress-v1|contour-http-proxy|ingress|none]`.
If not specified route is used when available, otherwise loadbalancer is used.
* `ingress-annotations - strings`            Annotations to add to skupper ingress
* `console-ingress - string`                 Determines if/how console is exposed outside cluster.
If not specified uses value of --ingress.
One of: `[route|loadbalancer|nodeport|nginx-ingress-v1|contour-http-proxy|ingress|none]`.
* `ingress-host - string`                    Hostname or alias by which the ingress route or proxy can be reached
* `router-mode - string`                     Skupper router-mode (default "interior")
* `annotations - strings`                    Annotations to add to skupper pods
* `labels - strings`                         Labels to add to skupper pods
* `enable-service-sync`                    Participate in cross-site service synchronization (default true)
* `enable-router-console`                  Enable router console
* `router-logging - string`                  Logging settings for router.
'trace', 'debug', 'info' (default), 'notice', 'warning', and 'error' are valid values.
* `router-debug-mode - string`               Enable debug mode for router ('asan' or 'gdb' are valid values)
* `routers int`                            Number of router replicas to start
* `router-cpu - string`                      CPU request for router pods
* `router-memory - string`                   Memory request for router pods
* `router-cpu-limit - string`                CPU limit for router pods
* `router-memory-limit - string`             Memory limit for router pods
* `router-node-selector - string`            Node selector to control placement of router pods
* `router-pod-affinity - string`             Pod affinity label matches to control placement of router pods
* `router-pod-antiaffinity - string`         Pod antiaffinity label matches to control placement of router pods
* `router-ingress-host - string`             Host through which node is accessible when using nodeport as ingress.
* `router-service-annotations - strings`     Annotations to add to skupper router service
* `router-load-balancer-ip - string`         Load balancer ip that will be used for router service, if supported by cloud provider
* `controller-cpu - string`                  CPU request for controller pods
* `controller-memory - string`               Memory request for controller pods
* `controller-cpu-limit - string`            CPU limit for controller pods
* `controller-memory-limit - string`         Memory limit for controller pods
* `controller-node-selector - string`        Node selector to control placement of controller pods
* `controller-pod-affinity - string`         Pod affinity label matches to control placement of controller pods
* `controller-pod-antiaffinity - string`     Pod antiaffinity label matches to control placement of controller pods
* `controller-ingress-host - string`         Host through which node is accessible when using nodeport as ingress.
* `controller-service-annotation - strings`  Annotations to add to skupper controller service
* `controller-load-balancer-ip - string`     Load balancer ip that will be used for controller service, if supported by cloud provider

.SEE ALSO

* xref:skupper.adoc[skupper]	 -
