= Skupper Documentation

This repo is used to document Skupper using https://docs.asciidoctor.org/asciidoc/latest/[AsciiDoc] markup.
The output is published at link:https://skupper.io/docs/index.html[Skupper - Documentation].


== Contributing to the documentation

This section explains how to edit and create documentation PRs.

If you only want to make a small update, you might want to just edit the file and make the PR using your standard process.

If you want to preview changes for more complex contributions, follow this procedure.

.Prerequisites

* link:https://docs.asciidoctor.org/asciidoctor/latest/install/[Install and Update | Asciidoctor Docs] 

.Procedure 


. Start the build:
+
----
$ python scripts/convert-all.py ./scripts/convert
-adoc.sh .github/workflows/asciidoc-convert-check.yml
----

* `convert-adoc.sh` converts each adoc to HTML
* `.github/workflows/asciidoc-convert-check.yml` is the single source of truth about which adoc files are published, see [GitHub: Source code for the Skupper project website]( https://github.com/skupperproject/skupper-website ).


. See the `build` directory for the HTML output.
