= Skupper Documentation

This repo is used to document Skupper using https://docs.asciidoctor.org/asciidoc/latest/[AsciiDoc] markup and https://docs.antora.org/[Antora].

Each Skupper function is an Antora module as seen at:
https://github.com/skupperproject/skupper-docs/tree/master/modules[]

The layout of files in each Antora module is:

* `/<antora-module>/pages` contains feature specific documentation, eg see `/modules/cli/pages` for CLI documentation.
* `/<antora-module>/assets/images` contains the image files used in the documentation, eg `/modules/console/assets/images`
* `/modules/ROOT/partials/attributes.adoc` contains variable definitions (AsciiDoc attributes) used by all docs.


== Contributing to the documentation

This section explains how to edit and create documentation PRs.
If you only want to make a small update, you might want to just edit the file and make the PR using your standard process.
If you are familiar with Antora, you can use the `preview-playbook.yml` directly.
If you want to preview changes for more complex contributions, follow this procedure.

.Prerequisites

* A Node LTS release (We recommend https://github.com/nvm-sh/nvm for installation)

.Procedure 

. Install the gulp cli:
+
----
npm install -g gulp-cli
----

. Install the dependencies:
+
----
npm install
----

. Start the build:
+
----
LIVERELOAD=true gulp
----

== Creating and running Didact tutorials

https://marketplace.visualstudio.com/items?itemName=redhat.vscode-didact[Didact] is a VS Code extension that allows you perform some procedures as interactive tutorials in VS Code.

To create the tutorials from this documentation:

. Install the https://marketplace.visualstudio.com/items?itemName=redhat.vscode-didact[Didact] extension in VS Code.

. Install the `autodidact` CLI:
+
----
$ npm i -g autodidact
----

. Convert the procedure you want to perform into Didact format:
+
----
$ autodidact modules/cli/pages/openshift.adoc
----
+
This creates the tutorial file:
+
----
modules/cli/pages/openshift.adoc.didact.adoc
----

. Run the tutorial by right clicking on the file in VS Code and choosing *Didact: Start Didact Tutorial from File*

