include::{mod-loc}attributes.adoc[]

//Category: skupper-cli
// Type: assembly

[id="skupper-cli"] 
= Configuring Skupper sites using the CLI

[role="system:abstract"]
Using the Skupper command-line interface (CLI) allows you to create and manage {skupper-name} sites from the context of the current namespace.

A typical workflow is to create a site, link sites together, and expose services to the {service-network}.

// tag::installing-cli[]
// Type: procedure
[id="installing-using-cli"] 
== Installing Skupper using the CLI

[role="system:abstract"]
Installing Skupper using the command-line interface (CLI) provides a simple method to get started with Skupper.

.Prerequisites

* Access to a Kubernetes cluster

.Procedure

. Install the Skupper command-line interface.
+
--
For Linux:
[subs=attributes+]
----
$ curl -fL https://github.com/skupperproject/skupper/releases/download//skupper-cli-0.3.2-linux-amd64.tgz | tar -xzf -
----

For MacOS:
[subs=attributes+]
----
$ curl -fL https://github.com/skupperproject/skupper/releases/download/{skupper-version}/skupper-cli-0.3.2-mac-amd64.tgz | tar -xzf -
----
--

. Copy the `skupper` executable to a directory in your $PATH:
+
----
$ mkdir -p $HOME/bin
$ export PATH=$PATH:$HOME/bin
$ mv skupper $HOME/bin
----

. Verify the installation.
+
[subs=attributes+]
----
$ skupper --version
skupper version {skupper-version}
----
// tag::installing-cli[]

// Type: procedure
[id="creating-using-cli"] 
== Creating a site using the CLI

A {service-network} consists of {skupper-name} sites.
This section describes how to create sites.

In the link:{getting-started-link}[tutorial], you create a site using the default settings:
----
$ skupper init
----

The default settings include:

* console - The {skupper-name} console is provisioned with a single user.
The password for the `admin` user is stored in the `skupper-console-users` secret.
* site name - The site name defaults to the namespace name, for example, `west`.

To create a custom site:

. Determine whether to provision the {skupper-name} console.
To disable the console:
+
----
$ skupper init --enable-console=false
----
+
For more information on the console, see link:{using-console-link}[Using the {skupper-name} console].

. Determine how to protect the {skupper-name} console.
There are a number of `skupper` options regarding authentication for the console:
+
--
`--console-auth <authentication-mode>`:: Set the authentication mode for the console:

* `openshift` - Use OpenShift authentication, so that users who have permission to log into OpenShift and view the Project (namespace) can view the console.
* `internal` -  Use {skupper-name} authentication, see the `console-user` and `console-password` options.
* `unsecured` - No authentication, anyone with the URL can view the console.


`--console-user <username>`:: Username for the console user when authentication mode is set to `internal`.
`--console-user <password>`:: Password for the console user when authentication mode is set to `internal`.
--

// Type: procedure
[id="linking-sites"] 
== Linking sites

A {service-network} consists of {skupper-name} sites.
This section describes how to link sites to form a {service-network}.

Linking two sites requires a single initial directional connection. However:

* Communication between the two sites is bidirectional, only the initial linking is directional.
* The choice of direction for linking is typically determined by accessibility. For example, if you are linking an OpenShift Dedicated cluster with a CodeReady Containers cluster, you must link from the CodeReady Containers cluster to the OpenShift Dedicated cluster because that route is accessible. 

.Procedure

. Determine the direction of the link. If both clusters are publicly addressable, then the direction is not significant. If one of the clusters is addressable from the other cluster, perform step 2 below on the addressable cluster.

. Generate a token on the cluster that you want to link to:
+
--
----
$ skupper token create <filename> 
----

where `<filename>` is the name of a YAML file that is saved on your local filesystem.

This file contains a key and the location of the site that created it.

NOTE: Access to this file provides access to the {service-network}. Protect it appropriately.
--

. Use a token to join the {service-network}:
+
--
----
$ skupper link create <filename> [-name <link-name>]
----
where where `<filename>` is the name of a YAML file generated from the `skupper token create` command and `<link-name>` is the name of the link.
--

. If you want to delete a link:
+
----
$ skupper link delete <link-name>
----
where `<link-name>` is the name of the link specified during creation.


// Type: procedure
[id="exposing-services"] 
== Exposing services on the {service-network}

After creating a {service-network}, services can communicate across that network.
This section describes how services can be enabled for a {service-network}.

.Procedure

. Create a deployment, some pods, or a service in one of your sites, for example to create the backend service for the link:{getting-started-link}[tutorial]:
+
----
$ kubectl create deployment hello-world-backend --image quay.io/skupper/hello-world-backend
----
+
This step is not {skupper-name}-specific, that is, this process is unchanged from standard processes for your cluster.


. Expose the service on the  {service-network} using the `expose` option:
+
--
----
$ skupper expose [deployment <name>|pods <selector>|service <name>]
----

where `<name>` is the name of your deployment or service and `<selector>` is a pod selector.

Options for this command include:

`--port <port-number>`:: Specify the port number that this service is available on the {service-network}.

`--target-port <port-number>`:: Specify the port number of pods that you want to expose.
--


// Type: reference
[id="cli-global-options"] 
== CLI options for working with different clusters

By default, all `skupper` commands apply to the cluster you are logged into and the current namespace.
The following `skupper` options allow you to override that behavior and apply to all commands:

`--namespace <namespace-name>`:: Apply command to `<namespace-name`. For example, if you are currently working on `frontend` namespace and want to initialize a site in the `backend` namespace:
+
----
$ skupper init --namespace backend
----
`--kubeconfig <kubeconfig-path>`:: Path to the kubeconfig file - This allows you run multiple sessions to a cluster from the same client. An alternative is to set the `KUBECONFIG` environment variable. See the link:{getting-started-link}[tutorial] for an example of using kubeconfig files.

`--context <context-name>`:: The kubeconfig file can contain defined contexts, and this option allows you to use those contexts.
