ifndef::mod-loc[]
:mod-loc: ./partials/
endif::mod-loc[]
include::{mod-loc}attributes.adoc[]

//Category: skupper-cli
// Type: assembly
[id="skupper-cli"] 
= Using the {skupper-name} CLI

include::{mod-loc}preface.adoc[]

Using the `skupper` command-line interface (CLI) allows you to create and manage {skupper-name} sites from the context of the current namespace.

A typical workflow is to create a site, link sites together, and expose services to the {service-network}.

include::installing.adoc[leveloffset=+1]

// Type: procedure
[id="creating-using-cli"] 
== Creating a site using the CLI

A {service-network} consists of {skupper-name} sites.
This section describes how to create a site using the default settings.

.Prerequisites

* The `skupper` CLI is installed.
* You are logged into the cluster.
* The services you want to expose on the {service-network} are in the active namespace.


.Procedure

. Create a default site:
+
----
$ skupper init
----

. Check the site:
+
----
$ skupper status

Skupper is enabled for namespace "west" in interior mode. It is not connected to any other sites.
----
+
NOTE: The default message above is displayed when you initialize a site on a cluster that does not have the {policy-system} installed.
If you install the {policy-system} as described in {skupperpolicybooklink}, the message becomes `Skupper is enabled for namespace "west" in interior mode (with policies)`.

The default site settings include:

* console - The Skupper console is provisioned with a single user.
The password for the `admin` user is stored in the `skupper-console-users` secret. 
For more information about the console, see {SkupperConsoleBookLink}.

* site name - The site name defaults to the namespace name, for example, `west`.

ifdef::product[]
include::{mod-loc}fragment-ingress.adoc[]
endif::[]

// Type: reference
[id="custom-sites"] 
== Custom sites

The default `skupper init` creates sites that satisfy typical requirements. 

If you require a custom configuration, note the following options:


* Creating a site without a console:
+
----
$ skupper init --enable-console false
----


* Configuring console authentication.
There are several `skupper` options regarding authentication for the console:
+
--
`--console-auth <authentication-mode>`:: Set the authentication mode for the console:

* `openshift` - Use OpenShift authentication, so that users who have permission to log into OpenShift and view the Project (namespace) can view the console.
* `internal` -  Use {skupper-name} authentication, see the `console-user` and `console-password` options.
* `unsecured` - No authentication, anyone with the URL can view the console.


`--console-user <username>`:: Username for the console user when authentication mode is set to `internal`.
Defaults to `admin`.
`--console-password <password>`:: Password for the console user when authentication mode is set to `internal`.
If not specified, a random passwords is generated.
--



* Configuring service access
+
--
----
$ skupper init --create-network-policy
----

NOTE: All sites are associated with a namespace, called the _active namespace_ in this procedure.

Services in the active namespace may be accessible to pods in other namespaces on that cluster by default, depending on your cluster network policies.
As a result, you can expose services to pods in namespaces not directly connected to the {service-network}. 
This setting applies a network policy to restrict access to services to those pods in the active namespace.

For example, if you create a site in the namespace `projectA` of `clusterA` and link that site to a {service-network} where the `database` service is exposed, the `database` service is available to pods in `projectB` of `clusterA`. 

You can use the `--create-network-policy` option to restrict the `database` service access to `projectA` of `clusterA`.

--

// Type: procedure
[id="linking-sites"] 
== Linking sites

A {service-network} consists of {skupper-name} sites.
This section describes how to link sites to form a {service-network}.

Linking two sites requires a single initial directional connection. However:

* Communication between the two sites is bidirectional, only the initial linking is directional.
* The choice of direction for linking is typically determined by accessibility. For example, if you are linking an OpenShift Dedicated cluster with a CodeReady Containers cluster, you must link from the CodeReady Containers cluster to the OpenShift Dedicated cluster because that route is accessible. 

.Procedure

. Determine the direction of the link. If both clusters are publicly addressable, then the direction is not significant. If one of the clusters is addressable from the other cluster, perform step 2 below on the addressable cluster.

. Generate a token on the cluster that you want to link to:
+
--
----
$ skupper token create <filename> 
----

where `<filename>` is the name of a YAML file that is saved on your local filesystem.

This file contains a key and the location of the site that created it.

[NOTE]
====
Access to this file provides access to the {service-network}. 
Protect it appropriately.

For more information about protecting access to the {service-network}, see {TokensLink}.
====
--

. Use a token on the cluster that you want to connect from:

.. Create a link to the {service-network}:
+
----
$ skupper link create <filename> [-name <link-name>]
----
+
where `<filename>` is the name of a YAML file generated from the `skupper token create` command and `<link-name>` is the name of the link.

.. Check the link:
+
----
$ skupper link status
Connection for link1 not active
----
+
In this example no <link-name> was specified, the name defaulted to `link1`.


. If you want to delete a link:
+
----
$ skupper link delete <link-name>
----
where `<link-name>` is the name of the link specified during creation.


// Type: concept
[id="exposing-services-ns"] 
== Exposing services on the {service-network} from a namespace

After creating a {service-network}, exposed services can communicate across that network.

The `skupper` CLI has two options for exposing services that already exist in a namespace:

* `expose` supports simple use cases, for example, a deployment with a single service.
See xref:exposing-simple-services[] for instructions.

* `service create` and `service bind` is a more flexible method of exposing services, for example, if you have multiple services for a deployment.
See xref:exposing-complex-services[] for instructions.


// Type: procedure
[id="exposing-simple-services"] 
=== Exposing simple services on the {service-network}
This section describes how services can be enabled for a {service-network} for simple use cases.

.Procedure

. Create a deployment, some pods, or a service in one of your sites, for example:
+
----
$ kubectl create deployment hello-world-backend --image quay.io/skupper/hello-world-backend
----
+
This step is not {skupper-name}-specific, that is, this process is unchanged from standard processes for your cluster.

. Create a service that can communicate on the {service-network}:
+
--
----
$ skupper expose [deployment <name>|pods <selector>|statefulset <statefulsetname>|service <name>]
----

where 

* `<name>` is the name of your deployment 
* `<selector>` is a pod selector
* `<statefulsetname>` is the name of a statefulset

For the example deployment in step 1, you create a service using the following command:
----
$ skupper expose deployment/hello-world-backend --port 8080
----

Options for this command include:

* `--port <port-number>`:: Specify the port number that this service is available on the {service-network}.
NOTE: You can specify more than one port by repeating this option.

* `--target-port <port-number>`:: Specify the port number of pods that you want to expose.

* `--protocol <protocol>` allows you specify the protocol you want to use, `tcp`, `http` or `http2`

--

NOTE: If you do not specify ports, `skupper` uses the `containerPort` value of the deployment.

// Type: procedure
[id="exposing-complex-services"] 
=== Exposing complex services on the {service-network}

This section describes how services can be enabled for a {service-network} for more complex use cases.

.Procedure

. Create a deployment, some pods, or a service in one of your sites, for example:
+
----
$ kubectl create deployment hello-world-backend --image quay.io/skupper/hello-world-backend
----
+
This step is not {skupper-name}-specific, that is, this process is unchanged from standard processes for your cluster.

. Create a service that can communicate on the {service-network}:
+
--
----
$ skupper service create <name> <port>
----

where 

* `<name>` is the name of the service you want to create
* `<port>` is the port the service uses

For the example deployment in step 1, you create a service using the following command:
----
$ skupper service create hello-world-backend 8080
----


--

. Bind the service to a cluster service:
+
--
----
$ skupper service bind <service-name> <target-type> <target-name>
----

where

* `<service-name>` is the name of the service on the {service-network}

* `<target-type>` is the object you want to expose, `deployment`, `statefulset`, `pods`, or `service`.

* `<target-name>` is the name of the cluster service

* `--protocol <protocol>` allows you specify the protocol you want to use, `tcp`, `http` or `http2`

For the example deployment in step 1, you bind the service using the following command:
----
$ skupper service bind hello-world-backend deployment hello-world-backend
----

--

// Type: procedure
[id="exposing-services-from-different-ns"] 
=== Exposing services from a different namespace to the {service-network}

This section shows how to expose a service from a namespace where {skupper-name} is not deployed.

.Prerequisites

* A namespace where {skupper-name} is deployed.
* A service running in a different namespace.
* A network policy that allows communication between the namespaces

. Log into your cluster and change to the namespace for your site.

. Expose the service on the {service-network}:
+
--
----
$ skupper expose service <service>.<namespace> --address <service>
----

* <service> - the name of the service on the {service-network}.
* <namespace> - the name of the namespace where the service you want to expose runs.

For example, if you deployed {skupper-name} in the `east` namespace and you created a `backend` service in the `east-backend` namespace, you set the context to the `east` namespace and expose the service as `backend` on the {service-network} using:

----
$ skupper expose service backend.east-backend --port 8080 --address backend
----

[NOTE]
====
You can only expose services from other namespaces.
If you want to expose a deployment from another namespace, create a service from the deployment before you try to expose it.
====
--


// Type: concept
[id="exposing-services-local"] 
== Exposing services on the {service-network} from a local machine

After creating a {service-network}, you can expose services from a local machine on the {service-network}.

For example, if you run a database on a server in your data center, you can deploy a front end in a cluster that can access the data as if the database was running in the cluster.

// Type: procedure
[id="exposing-service-gateway"] 
=== Exposing simple local services to the {service-network}

This section shows how to expose a single service running locally on a {service-network}.

.Prerequisites

* A {service-network}. Only one site is required.
* Access to the {service-network}.

ifdef::product[* `skrouterd` for the default `service` type gateways]

.Procedure

. Run your service locally. 

. Log into your cluster and change to the namespace for your site.

. Expose the service on the {service-network}:
+
--
----
$ skupper gateway expose <service> localhost <port>
----

* <service> - the name of the service on the {service-network}.
* <port> - the port that runs the service locally.

[NOTE]
====
You can also expose services from other machines on your local network, for example if MySQL is running on a dedicated server (with an IP address of `192.168.1.200`), but you are accessing the cluster from a machine in the same network:

----
$ skupper gateway expose mysql 192.168.1.200 3306
----
====
--

. Check the status of Skupper gateways:
+
--
----
$ skupper gateway status

Gateway Definition:
╰─ machine-user type:service version:1.18.0
   ╰─ Bindings:
      ╰─ mydb:3306 tcp mydb:3306 127.0.0.1 3306

----
This shows that there is only one exposed service and that service is only exposing a single port (BIND). There are no ports forwarded to the local host.

The URL field shows the underlying communication and can be ignored.
--

// Type: procedure
[id="exposing-services-gateway"] 
=== Working with complex local services on the {service-network}


This section shows more advanced usage of skupper gateway.

. Create a Skupper gateway:
+
--
[source,bash]
----
$ skupper gateway init --type <gateway-type>
----


ifdef::product[]
NOTE: The default service type gateway requires that `skrouterd` is running.
endif::[]

By default a _service_ type gateway is created, however you can also specify:

* `podman`
* `docker`
--

. Create a service that can communicate on the {service-network}:
+
--
----
$ skupper service create <name> <port>
----

where 

* `<name>` is the name of the service you want to create
* `<port>` is the port the service uses

For example:

----
$ skupper service create mydb 3306
----
--

. Bind the service on the {service-network}:
+
--
----
$ skupper gateway bind <service> <host> <port>
----

* <service> - the name of the service on the {service-network}, `mydb` in the example above.
* <host> - the host that runs the service.
* <port> - the port the service is running on, `3306` from the example above.
--

. Check the status of Skupper gateways:
+
--
----
$ skupper gateway status
Gateway Definitions Summary

Gateway Definition:
╰─ machine-user type:service version:1.18.0
   ╰─ Bindings:
      ╰─ mydb:3306 tcp mydb:3306 127.0.0.1 3306

----
This shows that there is only one exposed service and that service is only exposing a single port (BIND). There are no ports forwarded to the local host.

The URL field shows the underlying communication and can be ignored.

You can create more services in the {service-network} and bind more local services to expose those services on the {service-network}.  
--

. Forward a service from the {service-network} to the local machine.
+
--
----
$ skupper gateway forward <service> <port>
----

where 

* `<service>` is the name of an existing service on the {service-network}. 
* `<port>` is the port on the local machine that you want to use.

--


// Type: procedure
[id="exporting-gateway"] 
=== Creating a gateway and applying it on a different machine

If you have access to a cluster from one machine but want to create a gateway to the {service-network} from a different machine, you can create the gateway definition bundle on the first machine and later apply that definition bundle on a second machine as described in this procedure.
For example, if you want to expose a local database service to the {service-network}, but you never want to access the cluster from the database server, you can use this procedure to create the definition bundle and apply it on the database server.

.Procedure

. Log into your cluster from the first machine and change to the namespace for your site.


. Create a service that can communicate on the {service-network}:
+
--
----
$ skupper service create <name> <port>
----

where 

* `<name>` is the name of the service you want to create
* `<port>` is the port the service uses

For example:

----
$ skupper service create database 5432
----
--

. Create a YAML file to represent the service you want to expose, for example:
+
--
[source,yaml]
----
name: database <1>
bindings:
    - name: database <2>
      host: localhost <3>
      service:
        address: database:5432 <4>
        protocol: tcp <5>
        ports:
            - 5432 <6>
      target_ports:
        - 5432 <7>
qdr-listeners:
    - name: amqp
      host: localhost
      port: 5672
----
<1> Gateway name, useful for reference only.
<2> Binding name, useful to track multiple bindings.
<3> Name of host providing the service you want to expose.
<4> Service name and port on {service-network}. You created the service in a previous step. 
<5> The protocol you want to use to expose the service, `tcp`, `http` or `http2`.
<6> The port on the {service-network} that you want this service to be available on.
<7> The port of the service running on the host specified in point 3.

--

. Save the YAML file using the name of the gateway, for example, `gateway.yaml`.

. Generate a bundle that can be applied to the machine that hosts the service you want to expose on the {service-network}:
+
--
----
$ skupper gateway generate-bundle <config-filename> <destination-directory>
----

where:

* <config-filename> - the name of the YAML file, including suffix, that you generated in the previous step.
* <destination-directory> - the location where you want to save the resulting gateway bundle, for example `~/gateways`.

For example:
----
$ skupper gateway generate-bundle database.yaml ./
----

This bundle contains the gateway definition YAML and a  certificate that allow access to the {service-network}.

--

. Copy the gateway definition file, for example, `mylaptop-jdoe.tar.gz` to the machine that hosts the service you want to expose on the {service-network}.

. From the machine that hosts the service you want to expose:
+
--
----
$ mkdir gateway

$ tar -xvf <gateway-definition-file> --directory gateway
$ cd gateway
$ sh ./launch.py
----

NOTE: Use `./launch.py -t podman` or `./launch.py -t docker` to run the {skupper-router} in a container.

Running the gateway bundle uses the gateway definition YAML and a certificate to access and expose the service on the {service-network}.

--

. Check the status of the gateway service:
+
--

To check a _service_ type gateway:
----
$ systemctl --user status <gateway-definition-name>
----

To check a _podman_ type gateway:
----
$ podman inspect
----

To check a _docker_ type gateway:
----
$ docker inspect
----


NOTE: You can later remove the gateway using `./remove.py`.

--

. From the machine with cluster access, check the status of Skupper gateways:
+
--
----
$ skupper gateway status
Gateway Definitions Summary

NAME    BINDS  FORWARDS  URL                    
<machine-name>  1      0         amqp://127.0.0.1:5672 
----
This shows that there is only one exposed service and that service is only exposing a single port (BIND). There are no ports forwarded to the local host.
--

NOTE: If you need to change the gateway definition, for example to change port, you need to remove the existing gateway and repeat this procedure from the start to redefine the gateway.

// Type: procedure
[id="gateway-reference"] 
=== Gateway YAML reference

The xref:exporting-gateway[] describes how to create a gateway to apply on a separate machine using a gateway definition YAML file.

The following are valid entries in a gateway definition YAML file.

name:: Name of gateway
bindings.name:: Name of binding for a single host.
bindings.host:: Hostname of local service.
bindings.service:: Definition of service you want to be available on service network.
bindings.service.address:: Address on the service network, name and port.
bindings.service.protocol:: Skupper protocol, `tcp`, `http` or `http2`.
bindings.service.ports:: A single port that becomes available on the service network. 
bindings.service.target_ports:: A single port that you want to expose on the service network.

NOTE: If the local service requires more than one port, create separate bindings for each port.

forwards.name:: Name of forward for a single host.
forwards.host:: Hostname of local service.
forwards.service:: Definition of service you want to be available locally.
forwards.service.address:: Address on the service network that you want to use locally, name and port.
forwards.service.protocol:: Skupper protocol, `tcp`, `http` or `http2`.
forwards.service.ports:: A single port that is available on the service network. 
forwards.service.target_ports:: A single port that you want to use locally.

NOTE: If the network service requires more than one port, create separate forwards for each port.

qdr-listeners:: Definition of skupper router listeners
qdr-listeners.name:: Name of skupper router, typically `amqp`.
qdr-listeners.host:: Hostname for skupper router, typically `localhost`.
qdr-listeners.port:: Port for skupper router, typically `5672`.



include::./network-status.adoc[leveloffset=+1]

include::./native-security-options.adoc[leveloffset=+1]

include::./protocols.adoc[leveloffset=+1]

// Type: reference
[id="cli-global-options"] 
== CLI options for working with different clusters

By default, all `skupper` commands apply to the cluster you are logged into and the current namespace.
The following `skupper` options allow you to override that behavior and apply to all commands:

`--namespace <namespace-name>`:: Apply command to `<namespace-name>`. For example, if you are currently working on `frontend` namespace and want to initialize a site in the `backend` namespace:
+
----
$ skupper init --namespace backend
----
`--kubeconfig <kubeconfig-path>`:: Path to the kubeconfig file - This allows you run multiple sessions to a cluster from the same client. An alternative is to set the `KUBECONFIG` environment variable.

`--context <context-name>`:: The kubeconfig file can contain defined contexts, and this option allows you to use those contexts.
