include::{mod-loc}attributes.adoc[]

//Category: skupper-cli
// Type: assembly

[id="skupper-cli"] 
= Configuring Skupper sites using the CLI

[role="system:abstract"]
Using the Skupper command-line interface (CLI) allows you to create and manage {skupper-name} sites from the context of the current namespace.

A typical workflow is to create a site, link sites together, and expose services to the {service-network}.

// Type: procedure
[id="installing-using-cli"] 
== Installing Skupper using the CLI

[role="system:abstract"]
Installing Skupper using the command-line interface (CLI) provides a simple method to get started with Skupper.

.Prerequisites

* Access to a Kubernetes cluster

.Procedure

. Install the Skupper command-line interface.
+
--
For Linux:
[subs=attributes+]
----
$ curl -fL https://github.com/skupperproject/skupper/releases/download//skupper-cli-0.3.2-linux-amd64.tgz | tar -xzf -
----

For MacOS:
[subs=attributes+]
----
$ curl -fL https://github.com/skupperproject/skupper/releases/download/{skupper-version}/skupper-cli-0.3.2-mac-amd64.tgz | tar -xzf -
----
--

. Copy the `skupper` executable to a directory in your $PATH:
+
----
$ mkdir -p $HOME/bin
$ export PATH=$PATH:$HOME/bin
$ mv skupper $HOME/bin
----

. Verify the installation.
+
[subs=attributes+]
----
$ skupper --version
skupper version {skupper-version}
----


// Type: procedure
[id="creating-using-cli"] 
== Creating a site using the CLI

A {service-network} consists of {skupper-name} sites.
This section describes how to create sites.

In the link:getting


// Type: procedure
[id="linking-sites"] 
== Linking sites

A {service-network} consists of {skupper-name} sites.
This section describes how to link sites to form a {service-network}.


// Type: procedure
[id="exposing-services"] 
== Exposing services on the {service-network}

After creating a {service-network}, services can communicate across that network.
This section describes how services can be enabled for a {service-network}.





