ifndef::mod-loc[]
:mod-loc: ./partials/
endif::mod-loc[]
include::{mod-loc}attributes.adoc[]
:sectnums:
:kubernetes-flavor: OpenShift
//Category: openshift-tutorial
// Type: assembly
[id="openshift-tutorial"] 
= Creating a {service-network} with OpenShift and accessing a database using a Skupper gateway

[role="system:abstract"]
This tutorial demonstrates how to connect a frontend service on a OpenShift cluster with a backend service on a OpenShift cluster using the `skupper` command-line interface (CLI).
The backend service connects to a database running on your local machine.

.Prerequisites

* Access to projects in two OpenShift clusters, `cluster-admin` access is not required.
* One of the OpenShift clusters must be addressable from the other cluster.
* A MySQL database running on your local machine.

This tutorial shows how to connect the following namespaces:

* `west` - runs the frontend service and is typically a public cluster.
* `east` - runs the backend service.

NOTE: The backend service retrieves data from a database using a Skupper gateway.


include::{mod-loc}introduction-to-skupper.adoc[]

include::index.adoc[tags=installing-cli]


// Type: procedure
[id="creating-database"] 
== Creating a database

[role="system:abstract"]
This procedure describes how to create a database on your local machine that is accessed from the {service-network}.

.Prerequisites

* A demo MySQL database running on RHEL

.Procedure

NOTE: This procedure creates a user with a published password. Do not perform this procedure on a database with sensitive data.

. Log into MySQL and create the database using the following commands:
+
----
create database skupper;
use skupper database;
CREATE TABLE greetings (ID int, text varchar(255) );
INSERT INTO greetings VALUES (1,'Hello');
CREATE USER skupper@localhost IDENTIFIED BY 'reppuks';
GRANT SELECT  ON skupper.* TO 'skupper'@'localhost';
----

. Test the database by logging in as the `skupper` user and using the following commands:
+
----
use skupper database;
select * from greetings;
+------+-------+
| ID   | text  |
+------+-------+
|    1 | Hello |
+------+-------+
----

// Type: procedure
[id="configuring-consoles"] 
== Configuring terminal sessions

[role="system:abstract"]
This procedure describes how to configure your terminal sessions to use configurations to avoid problems as you configure {skupper-name} on different clusters.

The following table shows how you might set up your terminal sessions.

.Terminal sessions
[cols="1,1"]
|===
|west terminal session  |east terminal session

a|
[source,bash,subs="attributes+"]
----
 $ oc project
 west
----
a|
[source,bash,subs="attributes+"]
----
 $ oc project
 east
----


|===

.Prerequisites

* The OpenShift CLI is installed.
See the https://access.redhat.com/documentation/en-us/openshift_container_platform/4.6/html-single/cli_tools/index#installing-openshift-cli[OpenShift CLI] documentation for more instructions on how to install `oc`.

NOTE: In OpenShift 4.6 and later, you can use the web terminal to perform the following procedure, as described in the https://docs.openshift.com/container-platform/4.5/web_console/odc-about-web-terminal.html[web terminal] documentation.

.Procedure

. Start a terminal session to work on the `west` namespace and set the `KUBECONFIG` environment variable:
+
[source,bash,term=west]
----
$ export KUBECONFIG=$HOME/.kube/config-west
----
+
This session is referred to later as the _west_ terminal session.

// icon:cogs[] link:++didact://?commandId=workbench.action.terminal.split++[Split terminal] didactlink

// icon:cogs[] link:didact://?commandId=workbench.action.terminal.renameWithArg&json={&#34;name&#34;:&#34;east&#34;}[Rename terminal] didactlink

[start=2]
. Start a terminal session to work on the `east` namespace and set the `KUBECONFIG` environment variable:
+
[source,bash,term=east]
----
$ export KUBECONFIG=$HOME/.kube/config-east
----
+
This session is referred to later as the _east_ terminal session.

. In each terminal session, log into the OpenShift cluster, for example:
+
----
 $ oc login
----

// Type: procedure
[id="installing-skupper"] 
== Installing the {service-network} router in both clusters


. In the west terminal session:

.. Create the `west` project (namespace):
+
[source,bash,term=west]
----
$ oc new-project west 
----

.. Create the {service-network} router:
+
[source,bash,term=west]
----
$ skupper init
----

.. Check the site status:
+
--
[source,bash,term=west]
----
$ skupper status
----
The output should be similar to the following:
----
Skupper enabled for namespace 'west'. It is not connected to any other sites.
----
--


. In the east terminal session:
.. Create the `east` project (namespace):
+
[source,bash,term=east]
----
$ oc new-project east 
----

.. Create the {service-network} router:
+
[source,bash,term=east]
----
$ skupper init
----

.. Check the site status:
+
--
[source,bash,term=east]
----
$ skupper status
----
The output should be similar to the following:
----
Skupper enabled for namespace 'east'. It is not connected to any other sites.
----
--

// Type: procedure
[id="connecting-namespaces"] 
== Connecting namespaces to create a {service-network}

With the {service-network} routers installed, you can connect them together securely and allow service sharing across the {service-network}.

.Procedure

. In the west terminal session, create a connection token to allow connection to the west namespace:
+
[source,bash,term=west]
----
$ skupper token create $HOME/secret.yaml
----
+
This command creates the `secret.yaml` file in your home directory, which you can use to create the secure connection.

. In the east terminal session, use the token to create a connection to the west namespace:
+
[source,bash,term=east]
----
$ skupper link create $HOME/secret.yaml
----

. Check the site status from the west terminal session:
+
--
[source,bash,term=west]
----
$ skupper status
----
The output should be similar to the following:
----
Skupper is enabled for namespace "west" in interior mode. It is connected to 1 other site. It has no exposed services.
The site console url is:  https://<skupper-url>
The credentials for internal console-auth mode are held in secret: 'skupper-console-users'
----
--

// Type: procedure
[id="frontend"] 
== Creating the frontend service

The frontend service is a simple Python application that displays a message from the backend application.

.Procedure

Perform all tasks in the west terminal session:

. Deploy the frontend service:
+
[source,bash,term=west]
----
$ oc create deployment hello-world-frontend --image quay.io/pwright/hello-world-frontend
----

. Expose the frontend deployment as a cluster service:
+
[source,bash,term=west]
----
$ oc expose deployment hello-world-frontend --port 8080 --type LoadBalancer
----

. Create a route for the frontend:
+
[source,bash,term=west]
----
$ oc expose svc/hello-world-frontend
----

. Check the frontend route:
.. Get the route details:
+
--
[source,bash,term=west]
----
$  oc get routes
----

The output should be similar to the following:

----
NAME                   HOST/PORT                                   
hello-world-frontend   <frontend-url>       
----
--

.. Navigate to the `<frontend-url>` value in your browser, you see a message similar to the following because the frontend cannot communicate with the backend yet:
+
----
Trouble! HTTPConnectionPool(host='hello-world-backend', port=8080): Max retries exceeded with url: /api/hello (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbfcdf0d1d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
----
+
To resolve this situation, you must create the backend service and make it available on the {service-network}.

// Type: procedure
[id="backend"] 
== Creating the backend service and making it available on the {service-network}

The backend service runs in the `east` namespace and is not available on the {service-network} by default.
You use the `skupper` command to expose the service to all namespaces on the {service-network}.
The backend app is a simple Python application that passes a message to the frontend application.

.Procedure

. Deploy the backend service in the east terminal session:
+
[source,bash,term=east]
----
$ oc create deployment hello-world-backend --image quay.io/pwright/hello-world-backend
----

. Expose the backend service on the {service-network} from the east terminal session:
+
[source,bash,term=east]
----
$ skupper expose deployment hello-world-backend --port 8080 --protocol tcp
----

. Check the site status from the west terminal session:
+
--
[source,bash,term=west]
----
$ skupper status
----
The output should be similar to the following:
----
Skupper is enabled for namespace "west" in interior mode. It is connected to 1 other site. It has 1 exposed service.
----
The service is exposed from the `east` namespace.
--


. Create a route for the backend:
+
[source,bash,term=west]
----
$ oc expose svc/hello-world-backend
----


. Check the backend route in the east terminal session:

.. Get the route details:
+
--
[source,bash,term=east]
----
$  oc get routes
----

The output should be similar to the following:

----
NAME                   HOST/PORT                                   
hello-world-backend   <frontend-url>       
----
--

.. Navigate to the `<backend-url>` value in your browser, you see a message similar to the following:
+
----
Trouble! (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
----
+
To resolve this situation, you must create a Skupper gateway to make the database available on the {service-network}.


// Type: procedure
[id="gateway"] 
== Creating a Skupper gateway and making a database available on the {service-network}

.Procedure

. Create a gateway and make the database available on the {service-network}:
+
[source,bash,term=east]
----
$ skupper gateway expose mydb localhost 3306
----

// Type: procedure
[id="check"] 
== Checking database access from the frontend

.Procedure


. Check the frontend route in the west terminal session:

.. Get the route details:
+
--
[source,bash,term=west]
----
$  oc get routes
----

The output should be similar to the following:

----
NAME                   HOST/PORT                                   
hello-world-frontend   <frontend-url>       
----
--

.. Navigate to the `<frontend-url>` value in your browser, you see a message similar to the following:
+
----
I am the frontend.  The backend says 'Hello from database  (1)'.
----

This shows how the frontend calls the backend service over the {service-network} from a different OpenShift cluster.

.Additional resources

* {ConsoleLink}
* {CliLink}

// Type: procedure
[id="tearing-down"] 
== Tearing down the {service-network}

This procedure describes how to remove the {service-network} you created.

. Delete the `west` namespace from the west terminal session:
+
[source,bash,term=west]
----
$  oc delete project west
----


. Delete the `east` namespace from the east terminal session:
+
[source,bash,term=east]
----
$  oc delete project east
----



