ifdef::skupper-io[:image-prefix: ROOT:]
ifndef::mod-loc[]
:mod-loc: ./partials/
endif::mod-loc[]
include::{mod-loc}attributes.adoc[]
:sectnums:

//Category: gateway-tutorial
// Type: assembly
[id="openshift-tutorial"] 
= Creating a {service-network} with {kubernetes-flavor} and accessing a backend service using a Skupper gateway

[role="system:abstract"]
This tutorial describes how to connect a local backend service on a local machine with a frontend service running on a {kubernetes-flavor} cluster. 

In this tutorial, the services are the same as used in {OpenShiftTutoriallink}, however you run the backend service locally and expose the service on the service network using the `skupper` command-line interface (CLI).

.Prerequisites

* Access to a projects in a {kubernetes-flavor} cluster, `cluster-admin` access is not required.
* Python on your local machine.

This tutorial shows how to connect the following:

* `west` - a namespace in an accessible OpenShift cluster running the frontend service.
* `hello-world-backend` - a Python service running on a local machine.

NOTE: Although this tutorial demonstrates exposing a Python service on the {service-network}, a more typical use case would involve a database service, for example, MySQL.


// Type: concept
[id="introduction-to-skupper"] 
== Introduction to {skupper-name} {version}

ifdef::product[Interconnect 2.0 introduces a {service-network}, linking services across the hybrid cloud.]

A {service-network} enables communication between services running in different network locations. 
It allows geographically distributed services to connect as if they were all running in the same site.

image::{image-prefix}overview-gateway.svg[Overview of a service network]

For example, you can deploy your frontend in a public {kubernetes-flavor} cluster and deploy your backend on a local network, then connect them into a {service-network}.

You deploy and manage a {service-network}, including a gateway, using the `skupper` CLI.

.Additional resources

* {OverviewLink}


include::./installing.adoc[leveloffset=+1]


// Type: procedure
[id="creating-backend"] 
== Creating a backend service

[role="system:abstract"]
This procedure describes how to create a backend service on your local machine that is accessed from the {service-network}.

.Prerequisites

* Python

.Procedure

. Clone the link:https://github.com/skupperproject/skupper-example-hello-world[skupper-example-hello-world] repo.


. Change to the service directory.
+
[source,bash,term=local]
----
$ cd skupper-example-hello-world/backend/
----

. Install the required libraries.
+
[source,bash,term=local]
----
$ pip install --user flask starlette uvicorn

----

. Run the backend service
+
--
[source,bash,term=local]
----
$ python ./main.py
----
The output is similar to the following:

[source,bash,term=local]
----
INFO:     Started server process [107836]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
----
--

. Test the service by navigating to the following URL.
+
--
[source,bash,term=local]
----
http://localhost:8080/api/hello
----

The output is similar to the following:

[source,bash,term=local]
----
Hello from workstation (1)
----
This indicates that the backend service is running and available.
--

// Type: procedure
[id="configuring-consoles"] 
== Logging into cluster


.Prerequisites

* The kubectl CLI is installed.
+
ifdef::product[]
The `kubectl` CLI is automatically installed when you install `oc` as described in the link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.9/html-single/cli_tools/index#installing-openshift-cli[OpenShift CLI] documentation.
endif::[]


.Procedure

. Start a terminal session to work on the `west` namespace and set the `KUBECONFIG` environment variable:
+
[source,bash,term=west]
----
$ export KUBECONFIG=$HOME/.kube/config-west
----
+
This session is referred to later as the _west_ terminal session.

. Log into the {kubernetes-flavor} cluster.


// Type: procedure
[id="installing-skupper"] 
== Creating a skupper site

. Create the `west` namespace:
+
--
[source,bash,term=west]
----
$ kubectl create namespace west
$ kubectl config set-context --current --namespace west
----
--
. Create the {service-network} site:
+
[source,bash,term=west]
----
$ skupper init
----

. Check the site status:
+
--
[source,bash,term=west]
----
$ skupper status
----
The output should be similar to the following:
----
Skupper enabled for namespace 'west'. It is not connected to any other sites.
----
--



// Type: procedure
[id="frontend"] 
== Creating the frontend service

The frontend service is a simple Python application that displays a message from the backend application.

.Procedure

Perform all tasks in the west terminal session:

. Deploy the frontend service:
+
[source,bash,term=west]
----
$ kubectl create deployment hello-world-frontend --image quay.io/skupper/hello-world-frontend
----

. Expose the frontend deployment as a cluster service:
+
[source,bash,term=west]
----
$ kubectl expose deployment hello-world-frontend --port 8080 --type LoadBalancer
----

. Create a route for the frontend:
+
[source,bash,term=west]
----
$ oc expose svc/hello-world-frontend
----

. Check the frontend route:
.. Get the route details:
+
--
[source,bash,term=west]
----
$  oc get routes
----

The output should be similar to the following:

----
NAME                   HOST/PORT                                   
hello-world-frontend   <frontend-url>       
----
--

.. Navigate to the `<frontend-url>` value in your browser, you see a message similar to the following because the frontend cannot communicate with the backend yet:
+
----
Trouble! HTTPConnectionPool(host='hello-world-backend', port=8080): Max retries exceeded with url: /api/hello (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbfcdf0d1d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
----
+
To resolve this situation, you must make the backend service available on the {service-network} using a gateway.

// Type: procedure
[id="gateway"] 
== Creating and using a Skupper gateway

This procedure describes how to create a gateway and make a backend service available on the {service-network}.

.Prerequisites

* Skupper router is installed on local machine

.Procedure

. Create a gateway:
+
[source,bash,term=west]
----
$ skupper gateway init --type podman
----

. Create a {skupper-name} service:
+
[source,bash,term=west]
----
$ skupper service create hello-world-backend 8080
----

. Bind the local backend service to the {skupper-name} service:
+
--
[source,bash,term=west]
----
$ skupper gateway bind hello-world-backend <backend-ip-address> 8080
----
where the <backend-ip-address is the address you noted in xref:creating-backend[]

--

. Check the gateway status:
+
--
[source,bash,term=west]
----
$ skupper gateway status
----

The output should be similar to following:

[source,bash,term=west]
----
Gateway Definitions:
╰─ <machine>-<user> type: podman version: 1.17.1
 ╰─ Bindings:
    ╰─ hello-world-backend:8080 tcp hello-world-backend:8080 <backend-ip-address> 8080

----
--

// Type: procedure
[id="check"] 
== Checking service access from the frontend

.Procedure

. Get the URL details:
+
--
[source,bash,term=west]
----
$ kubectl get service hello-world-frontend -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
----

Use the output IP address to construct the <frontend-url>:
----
<cluster-ip-address>:8080/
----
--

. Navigate to the `<frontend-url>` value in your browser, you see a message similar to the following:
+
----
I am the frontend.  The backend says 'Hello from <machine> 1)'.
----


This shows how the frontend calls the backend over the {service-network} from an {kubernetes-flavor} cluster.

.Additional resources

* {ConsoleLink}
* {CliLink}

// Type: procedure
[id="tearing-down"] 
== Tearing down the {service-network}

This procedure describes how to remove the {service-network} you created.

. Delete the gateway:
+
[source,bash,term=west]
----
$  skupper gateway delete 
----


. Delete the `west` namespace from the west terminal session:
+
[source,bash,term=west]
----
$  kubectl namespace delete west
----

