include::{mod-loc}attributes.adoc[]

:context: skupper-podman
//Category: skupper-cli
// Type: assembly
[id='using-skupper-podman-{context}']
= Using Skupper podman

[role="system:abstract"]
Skupper podman allow you to create a site using containers, without requiring Kubernetes.
Typically, you create a site on a Linux host, allowing you to link to and from other sites, regardless of whether those sites are running in podman or Kubernetes.

NOTE: This is a preview feature and may change before becoming fully supported by https://skupper.io[skupper.io].


[id='about-{context}']
== About Skupper podman

Skupper podman is available from the CLI using:

`skupper switch podman`:: If you enter this command, all subsequent command target podman rather than Kubernetes.
+
--
To determine which mode is currently active:

----
$ skupper switch

podman
----

To switch back to target Kubernetes sites: `skupper switch kubernetes`
--

`skupper --platform podman`:: Use this option to avoid changing mode, for example, if you are working on Kubernetes and podman simultaneously.

`export SKUPPER_PLATFORM=podman`:: Use this command to use Skupper podman for the current session, for example, if you have two terminals set to different contexts. To set the environment to target Kubernetes sites:

----
$ export SKUPPER_PLATFORM=kubernetes
----


[id='creating-a-site-{context}']
== Creating a site using Skupper podman

.Prerequisites

* The `skupper` CLI is installed.
* Podman is installed, see https://podman.io/


. Set your session to use Skupper podman:
+
--
----
$ export SKUPPER_PLATFORM=podman
----

To verify the `skupper` mode:

----
$ skupper switch

podman
----

--

. Create a Skupper site:
+
--
The simplest Skupper site allows you to link to other sites, but does not support linking _to_ the current site.

----
$ skupper init --ingress none

It is recommended to enable lingering for <username>, otherwise Skupper may not start on boot.
Skupper is now installed for user '<username>'.  Use 'skupper status' to get more information.
----

If you require that other sites can link to the site you are creating:

----
$ skupper init --ingress-host <machine-address>

It is recommended to enable lingering for <username>, otherwise Skupper may not start on boot.
Skupper is now installed for user '<username>'.  Use 'skupper status' to get more information.
----

For more information, see xref:cli-podman:skupper_init.adoc[podman skupper init].

--

. Check the status of your site:
+
--
----
$ skupper status
Skupper is enabled for "<username>" with site name "<machine-name>-<username>" in interior mode. It is not connected to any other sites. It has no exposed services.
----

NOTE: You can only create one site per user. If your require a host to support many sites, create a user for each site.

--


== Linking sites using Skupper podman

The general flow for linking podman sites is the same as for Kubernetes sites:

. Generate a token on one site:
+
----
$ skupper token create <filename>
----

. Create a link from the other site:
+
----
$ skupper link create <filename>
----

After you have linked to a network, you can view the exposed services:

----
$ skupper service status
----


== Exposing services using Skupper podman

The general flow for exposing services is the same as Kubernetes for podman sites, for example:

----
$ skupper expose  <service> <port>
----

For more information, see xref:cli-podman:skupper_expose.adoc[podman skupper expose].