// Type: procedure
[id='network-service']
== Exploring a {service-network}

Skupper includes a command to allow you report all the sites and the services available on a {service-network}.

.Prerequisites

* A {service-network} with more than one site

.Procedure

. Set your Kubernetes context to a namespace on the {service-network}.

. Use the following command to report the status of the {service-network}:
+
--

[source,bash]
----
$ skupper network status
----

For example:

[source]
----
Sites:
├─ [local] a960b766-20bd-42c8-886d-741f3a9f6aa2(west) <1>
│  │ namespace: west
│  │ site name: west <2>
│  │ version: 1.5.1 <3>
│  ╰─ Linked sites:
│     ├─ 496ca1de-0c80-4e70-bbb4-d0d6ec2a09c0(east)
│     │  direction: outgoing
│     ╰─ 484cccc3-401c-4c30-a6ed-73382701b18a()
│        direction: incoming
├─ [remote] 496ca1de-0c80-4e70-bbb4-d0d6ec2a09c0(east) <4>
│  │ namespace: east
│  │ site name: east
│  │ version: 1.5.1
│  ╰─ Linked sites:
│     ╰─ a960b766-20bd-42c8-886d-741f3a9f6aa2(west) <5>
│        direction: incoming
╰─ [remote] 484cccc3-401c-4c30-a6ed-73382701b18a() <6>
   │ site name: vm-user-c3d98
   │ version: 1.5.1
   ╰─ Linked sites:
      ╰─ a960b766-20bd-42c8-886d-741f3a9f6aa2(west)
         direction: outgoing
----

<1> The unique identifier of the site associated with the current context, that is, the `west` namespace

<2> The site name.
By default, skupper uses the name of the current namespace.
If you want to specify a site name, use `skupper init  --site-name <site-name>`.

<3> The version of Skupper running the site.
The site version can be different from the current `skupper` CLI version.
To update a site to the version of the CLI, use `skupper update`.

<4> The unique identifier of a remote site on the {service-network}.

<5> The sites that the remote site is linked to.

<6> The unique identifier of a remote podman site. Podman sites do not have an associated context.

--