include::../partials/attributes.adoc[]
//Category: skupper-cli
// Type: assembly
[id='using-skupper-podman']
= Using Skupper Podman

Using the `skupper` command-line interface (CLI) allows you to create and manage Skupper sites from the context of the current Linux user.
Skupper Podman allows you to create a site using containers, without requiring Kubernetes.

A typical workflow is to create a site, link sites together, and expose services to the {service-network}.

[id='about']
== About Skupper Podman

Skupper Podman is available with the following precedence:

`skupper --platform podman <command>`:: Use this option to avoid changing mode, for example, if you are working on Kubernetes and Podman simultaneously.

`export SKUPPER_PLATFORM=podman`:: Use this command to use Skupper Podman for the current session, for example, if you have two terminals set to different contexts. To set the environment to target Kubernetes sites:
+
[source, bash]
----
$ export SKUPPER_PLATFORM=kubernetes
----

`skupper switch podman`:: If you enter this command, all subsequent command target Podman rather than Kubernetes for all terminal sessions.


To determine which mode is currently active:
[source, bash]
----
$ skupper switch
 
podman
----

To switch back to target Kubernetes sites: `skupper switch kubernetes`



[NOTE]
====
Services exposed on remote sites are not automatically available to Podman sites.
This is the equivalent to Kubernetes sites created using `skupper init --enable-service-sync false`.

To consume an exposed service on a Podman site, check that it exists using `skupper service status` on the original site and use that information to create the service on the Podman site:
[source, bash]
----
$ skupper service create <name> <port>
----
====


[id='creating-a-site']
== Creating a site using Skupper podman

A {service-network} consists of Skupper sites.
This section describes how to create a site in on a Linux host using the default settings.
See link:{cli-link} for information about using the Skupper CLI to create Podman sites.


.Prerequisites

* The latest `skupper` CLI is installed.
* Podman is installed, see https://podman.io/
+
--
By default, Podman v4 uses Netavark which works with Skupper.
If you are using CNI, for example, if you upgrade from Podman v3, you must also install the `podman-plugins` package.
For example, `dnf install podman-plugins` for RPM based distributions.

NOTE: CNI will be deprecated in the future in preference of Netavark.
--
* Podman service endpoint.
+
--
Use `systemctl status podman.socket` to make sure the Podman API Socket is running.

Use `systemctl --user enable --now podman.socket` to start the  Podman API Socket.

See link:https://github.com/containers/podman/blob/main/docs/tutorials/socket_activation.md[Podman socket activation] for information about enabling this endpoint.
--


. Set your session to use Skupper Podman:
+
--
[source, bash]
----
$ export SKUPPER_PLATFORM=podman
----

To verify the `skupper` mode:

[source, bash]
----
$ skupper switch

podman
----

--

. Create a Skupper site:
+
--

Use the following command to create a site where tokens are created to link on any network interface:

[source, bash]
----
$ skupper init
----

NOTE: By default, this command times out after 2 minutes for podman sites.
You can increase the time with the `--timeout` option.

The following output is displayed:

[source, bash]
----
It is recommended to enable lingering for <username>, otherwise Skupper may not start on boot.
Skupper is now installed for user '<username>'.  Use 'skupper status' to get more information.
----

Use the following command to start the site service at system start and persist over logouts:

[source, bash]
----
# loginctl enable-linger <username>
----

By default, `skupper init` tries to include all IP addresses associated with local network interfaces as valid ingress hosts.
You can use `--ingress-host <IP/Hostname>` to restrict token ingress to a specific network context:

[source, bash]
----
$ skupper init --ingress-host my-cloud-vm.example.com
----

If you do not require that other sites can link to the site you are creating:

[source, bash]
----
$ skupper init --ingress none
----

In this guide we assume you have enabled ingress using the first command.
This allows you create tokens that allow links from every network interface on the host.

NOTE: When creating a token you can specify the ingress host.

You can also restrict ingress to an IP address or hostname when initializing as described in the link:{pod-ref-link} documentation.
--

. Check the status of your site:
+
--
[source, bash]
----
$ skupper status
Skupper is enabled for "<username>" with site name "<machine-name>-<username>" in interior mode. It is not connected to any other sites. It has no exposed services.
----

NOTE: You can only create one site per user. If you require a host to support many sites, create a user for each site.

--


== Linking sites using Skupper Podman


A {service-network} consists of Skupper sites.
This section describes how to link sites to form a {service-network}.

Linking two sites requires a single initial directional connection. However:

* Communication between the two sites is bidirectional, only the initial linking is directional.
* The choice of direction for linking is typically determined by accessibility. For example, if you are linking a virtual machine running in the cloud with a Linux host running behind a firewall, you must link from the Linux host to the cloud virtual machine because that route is accessible. 

.Procedure

. Generate a token on one site:
+
--
[source, bash]
----
$ skupper token create <filename>
----

If you created the site  without specifying an `ingress-host`, the token is valid for all network contexts.
You can use `--ingress-host <IP/Hostname>` to restrict token ingress to a specific network context:

[source, bash]
----
$ skupper token create <filename> --ingress-host <IP/Hostname>
----

--

. Create a link from the other site:
+
[source, bash]
----
$ skupper link create <filename>
----

After you have linked to a network, you can check the link status:
[source, bash]
----
$ skupper link status
----

include::link-cost.adoc[leveloffset=0]

// Type: concept
[id="podman_exposing-services-ns"] 
== Exposing services on the {service-network} from a Linux host

After creating a {service-network}, exposed services can communicate across that network.

The general flow for working with services is the same for Kubernetes and Podman sites.

The `skupper` CLI has two options for exposing services that already exist on a host:

* `expose` supports simple use cases, for example, a host with a single service.
See xref:podman_exposing-simple-services[] for instructions.

* `service create` and `service bind` is a more flexible method of exposing services, for example, if you have multiple services for a host.
See xref:podman_exposing-complex-services[] for instructions.

// Type: procedure
[id="podman_exposing-simple-services"] 
=== Exposing simple services on the {service-network}
This section describes how services can be enabled for a {service-network} for simple use cases.

.Prerequisites 

* A Skupper Podman site

.Procedure

. Run a server, for example:
+
[source, bash]
----
$ podman run --name backend-target --network skupper --detach --rm -p 8080:8080 quay.io/skupper/hello-world-backend
----
+
This step is not Skupper-specific, that is, this process is unchanged from standard processes for your host.


. Create a service that can communicate on the {service-network}:
+
--
[source, bash]
----
$ skupper expose [host <hostname|ip>]
----

where 

* `<host>` is the name of the host where the server is running. 
For example, the name of the container if you run the server as a container.
* `<ip>` is the IP address where the server is running

For the example deployment in step 1, you create a service using the following command:
----
$ skupper expose host backend-target --address backend --port 8080
----

Options for this command include:

* `--port <port-number>`:: Specify the port number that this service is available on the {service-network}.
NOTE: You can specify more than one port by repeating this option.

* `--target-port <port-number>`:: Specify the port number of pods that you want to expose.

* `--protocol <protocol>` allows you specify the protocol you want to use, `tcp`, `http` or `http2`

--

. Create the service on another site in the {service-network}:
+
[source, bash]
----
$ skupper service create backend 8080
----


// Type: procedure
[id="podman_exposing-complex-services"] 
=== Exposing complex services on the {service-network}

This section describes how services can be enabled for a {service-network} for more complex use cases.

.Prerequisites 

* A Skupper Podman site

.Procedure

. Run a server, for example:
+
[source, bash]
----
$ podman run --name backend-target --network skupper --detach --rm -p 8080:8080 quay.io/skupper/hello-world-backend
----
+
This step is not Skupper-specific, that is, this process is unchanged from standard processes for your host.

. Create a service that can communicate on the {service-network}:
+
--
[source, bash]
----
$ skupper service create <name> <port>
----

where 

* `<name>` is the name of the service you want to create
* `<port>` is the port the service uses

For the example deployment in step 1, you create a service using the following command:
[source, bash]
----
$ skupper service create hello-world-backend 8080
----


--

. Bind the service to a cluster service:
+
--
[source, bash]
----
$ skupper service bind <service-name> <target-type> <target-name>
----

where

* `<service-name>` is the name of the service on the {service-network}

* `<target-type>` is the object you want to expose, `host` is the only current valid value.

* `<target-name>` is the name of the cluster service

For the example deployment in step 1, you bind the service using the following command:
[source, bash]
----
$ skupper service bind hello-world-backend host hello-world-backend
----

--


// Type: procedure
[id="consuming-simple-services"] 
=== Consuming simple services from the {service-network}

Services exposed on Podman sites are not automatically available to other sites.
This is the equivalent to Kubernetes sites created using `skupper init --enable-service-sync false`.

.Prerequisites

* A remote site where a service is exposed on the {service-network}
* A Podman site

.Procedure

. Log into the host as the user associated with the Skupper site.

. Create the local service:
+
--
[source, bash]
----
$ skupper service create <service-name> <port number>
----
--

== Deleting a Podman site

When you no longer want the Linux host to be part of the {service-network}, you can delete the site.

[NOTE]
====
This procedure removes all containers, volumes and networks labeled `application=skupper`.

To check the labels associated with running containers:

[source, bash]
----
$ podman ps -a --format "{{.ID}}  {{.Image}}  {{.Labels}}" 
----
====

.Procedure

. Make sure you are logged in as the user that created the site:
+
--
[source, bash]
----
$ skupper status
Skupper is enabled for "<username>" with site name "<machine-name>-<username>".
----
--

. Delete the site and all podman resources (containers, volumes and networks) labeled with "application=skupper":
+
--
[source, bash]
----
$ skupper delete
Skupper is now removed for user "<username>".
----
--