...@common

shape: sequence_diagram

Site 1.note: Access grant

Site 1 -> Site 2: Issue token

Site 2.note: Access token

Site 2 -> Site 1: Redeem token

Site 1 -> Site 2: Transfer link details
Site 2 -> Site 1: Create link

Site*.class: neutral
