...@common

Site namespace.Attached connector binding <-> Connector namespace.Attached connector

Connector namespace: {
  Attached connector -> Server 1
  Attached connector -> Server 2
  Attached connector -> Server 3
}

Routing key -- Site namespace.Attached connector binding

Routing key.class: notion
Site namespace*.class: neutral
Connector namespace*.class: neutral
Connector namespace.Server*.style.fill: white
