classes: {
  notion: {
    style: {
      stroke-width: 1
      fill: "#eee"
      bold: false
      italic: true
    }
  }

  neutral: {
    style: {
      stroke-width: 1
      fill: "#eee"
      font-size: 16
    }
  }

  context: {
    style: {
      stroke-width: 1
      stroke-dash: 5
      stroke: "#a0a0a0"
      fill: "#f3f3f3"
      font-size: 16
      font-color: "#a0a0a0"
    }
  }

  canvas: {
    label: ""
    style: {
      stroke-width: 0
      fill: "#f3f3f3"
    }
  }

  hidden.style.opacity: 0
}

direction: right
