...@common

Site -- Connector: {
  source-arrowhead: 1
  target-arrowhead: n
}

Connector -- Workload: {
  source-arrowhead: n
  target-arrowhead: 1
}

Connector -- Routing key: {
  source-arrowhead: n
  target-arrowhead: 1
}
