...@common

Site 1.class: neutral
Site 1.Database\nclient.style.fill: white

Site 2.class: neutral
Site 2.Database\nclient.style.fill: white

Connectors.class: notion

Site 1.Database\nclient -> Site 1.Listener -- Routing key\n\"database\" -- Connectors

Site 2.Database\nclient -> Site 2.Listener -- Routing key\n\"database\"
