...@common

direction: down

Platform -- Site: {
  source-arrowhead: 1
  target-arrowhead: n
}

Network -- Site: {
  source-arrowhead: 1
  target-arrowhead: n
}

Site -- Workload: {
  source-arrowhead: 1
  target-arrowhead: n
}

Site -- "Link ": {
  source-arrowhead: 1
  target-arrowhead: n
}

Site -- Listener: {
  source-arrowhead: 1
  target-arrowhead: n
}

Site -- Connector: {
  source-arrowhead: 1
  target-arrowhead: n
}
