...@common

Canvas.class: canvas

Canvas: {
  Platform 1: {
    Namespace 1.Site
    Namespace 2.Site
  }

  Platform 2: {
    Namespace 1.Site
    Namespace 2.Site
  }

  Platform 1.Namespace 1.Site -- Platform 2.Namespace 1.Site
  Platform 1.Namespace 2.Site -- Platform 2.Namespace 2.Site
}
