...@common

Platform -- Namespace: {
  source-arrowhead: 1
  target-arrowhead: n
}

Namespace -- Workload: {
  source-arrowhead: 1
  target-arrowhead: n
}

Namespace -- Site: {
  source-arrowhead: 1
  target-arrowhead: 0..1
}
