...@common

Site 1.Client -> Site 1.Listener -- Routing key
Site 2.Client -> Site 2.Listener -- Routing key

Routing key -- Site 3.Connector -> Site 3.Server

Routing key.class: notion
Site*.Client*.style.fill: white
Site*.Server*.style.fill: white
Site*.class: neutral