include::{mod-loc}attributes.adoc[]

//Category: skupper-declarative
// Type: assembly
[id="skupper-declarative"] 
= Configuring Skupper sites using YAML


[role="system:abstract"]
Using YAML files to configure Skupper allows you to use source control to track and manage Skupper network changes.


// Type: procedure
[id="installing-using-yaml"] 
== Installing Skupper using YAML

[role="system:abstract"]
Installing Skupper using YAML provides a declarative method to install Skupper.
You can store your YAML files in source control to track and manage Skupper network changes.

.Prerequisites

* Access to a Kubernetes cluster

.Procedure

. Log into your cluster.
If you are deploying Skupper to be available for all namespaces, make sure you have `cluster-admin` privileges.

. Deploy the site controller:

.. To install Skupper into the current namespace deploy the site controller using the following YAML:
+
[subs=attributes+]
----
kubectl apply -f https://raw.githubusercontent.com/skupperproject/skupper/{skupper-version}/cmd/site-controller/deploy-watch-current-ns.yaml
----

.. To install Skupper for all namespaces, deploy the site controller using the following YAML:
+
[subs=attributes+]
----
kubectl apply -f https://raw.githubusercontent.com/skupperproject/skupper/{skupper-version}/cmd/site-controller/deploy-watch-all-ns.yaml
----

. Verify the installation.
+
----
$ oc get pods
NAME                                       READY   STATUS    RESTARTS   AGE
skupper-site-controller-84694bdbb5-n8slb   1/1     Running   0          75s
----

// Type: procedure
[id="creating-using-yaml"] 
== Creating a Skupper site using YAML
