include::{mod-loc}attributes.adoc[]

//Category: skupper-policy
// Type: assembly
[id="skupper-policy"] 
= Securing a {service-network}

By default, {skupper-name} includes many security features.
If you apply the {policy-system}, all communication is denied, and you can specify granular policies to allow your {service-network} operate.

{skupper-name} provides default, built-in security that scales across clusters and clouds. 
In a {service-network}, the communication between sites is performed by {skupper-router}s and is secured with mutual TLS using a private, dedicated certificate authority (CA). 
Each {skupper-router} is uniquely identified by its own certificate.
This means that the {service-network} is isolated from external access, preventing security risks such as lateral attacks, malware infestations, and data exfiltration.


// Type: concept
[id="about-skupper-policies"] 
== About the {policy-system}

After installing the {policy-system} Custom Resource Definition (CRD), you need to configure one or more of the following items using custom resources (CRs) to enable communication:

Allow incoming links:: Use `AllowIncomingLinks` to enable users create tokens and configure incoming links.

Allow outgoing links to specific hosts:: Use `allowedOutgoingLinksHostnames` to specify hosts that users can create links to.

Allow services:: Use `allowedServices` to specify which services can be created or used on the {service-network}.

Allow resources to be exposed:: Use `allowedExposedResources` to specify which service bindings can be created or used on the {service-network}.

NOTE: Each setting for the {policy-system} can be applied to one or more namespaces.

For example, the following policy CR disallows outgoing links for all namespaces, but all other {skupper-name} capabilities are allowed:

[source,yaml]
----
apiVersion: skupper.io/v1alpha1
kind: SkupperClusterPolicy
metadata:
  name: cluster-policy-sample-01
spec:
  namespaces:
    - "*"
  allowIncomingLinks: true
  allowGateway: true
  allowedExposedResources:
    - "*"
  allowedOutgoingLinksHostnames: []
  allowedServices:
    - "*"
----

`namespaces`:: One or more patterns to specify the namespaces that this policy applies to.

`allowIncomingLinks`:: Specify `true` or `false` to determine whether other sites can create links to the namespaces specified.

`allowedOutgoingLinksHostnames`:: Specify one or more patterns to determine which hosts you can create links to from the namespaces specified.

`allowedServices`:: Specify one or more patterns to determine the permitted names of services allowed on the {service-network} from the namespaces specified.

`allowedExposedResources`:: Specify one or more patterns to determine the permitted names of service bindings allowed on the {service-network} from the namespaces specified.

[TIP]
====
Use regular expressions to create matches, for example:

* `.*/.com` matches any string ending in `.com`.
* `^abc$` matches the string `abc`.

====

If you create another CR that allows outgoing links for a specific namespace, a user can create a link from that namespace to join a {service-network}, that is, the logic for multiple policy CRs is `OR`.
{skupper-name} allows operations if one or more of the policy CRs permits the operation.

// Type: procedure
[id="installing-crd"] 
== Installing the {policy-system} CRD

Install the {policy-system} CRD enables a cluster administrator enforce policies for {service-network}s.

NOTE: If there are existing sites on the cluster, see xref:installing-crd-existing-sites[]

.Prerequisites

* Access to a cluster using a `cluster-admin` account
* The operator is installed in {OperatorLink}
.Procedure

. Log into the cluster using a `cluster-admin` account.

. Download the CRD.

. Apply the CRD:
+
[source,yaml]
----
$ kubectl apply -f skupper_cluster_policy_crd.yaml

customresourcedefinition.apiextensions.k8s.io/skupperclusterpolicies.skupper.io created
clusterrole.rbac.authorization.k8s.io/skupper-service-controller created
----

// to be modified soon
. Create a rolebinding in all namespaces.

. To verify that the {policy-system} is active, use the `skupper status` command and check that the output includes the following line:
+
[source,bash]
----
Skupper policy is enabled
----

// Type: procedure
[id="installing-crd-existing-sites"] 
== Installing the {policy-system} CRD on a cluster with existing sites

If the cluster already hosts {skupper-name} sites, note the following before installing the CRD:

* All existing connections are closed. 
You must apply a policy CR to reopen connections
* All existing {service-network} services and service bindings are removed. 
You must create those resources again.

.Procedure

To avoid disruption:

. Plan the CRD deployment for an appropriate time.

. Search your cluster for sites:
+
[source,bash]
----
$ kubectl get pods --all-namespaces --selector=app=skupper
----

. Document each service and service binding.

. Install the CRD as described in xref:installing-crd[].
This step closes connections and removes all {service-network} services and service bindings.

. Create policy CRs as described in xref:

. Recreate any services and service bindings as required.


// Type: procedure
[id="creating-policies"] 
== Creating policies for the {policy-system}

Policies allow you control communication across the {service-network} from a cluster.


.Prerequisites

* Access to a cluster using a `cluster-admin` account
* The {policy-system} CRD is installed on the cluster

.Procedure

NOTE: Typically, you create a policy CR that combines many elements from the steps below, for example, see xref:about-skupper-policies[]

. xref:AllowIncomingLinks[]
. xref:allowedOutgoingLinksHostnames[]
. xref:allowedServices[]
. xref:allowedExposedResources[]

// Type: procedure
[id="AllowIncomingLinks"] 
=== Implement a policy to allow incoming links

Use `AllowIncomingLinks` to enable users create tokens and configure incoming links.

.Procedure

. Determine which namespaces you want to apply this policy to.
. Create a CR with `AllowIncomingLinks` set to `true` or `false`.
. Create and apply the CR.

For example, the following CR disallows incoming links for all namespaces: 
[source,yaml]
----
apiVersion: skupper.io/v1alpha1
kind: SkupperClusterPolicy
metadata:
  name: AllowIncomingLinks
spec:
  namespaces:
    - "*"
  allowIncomingLinks: true
----




// Type: procedure
[id="allowedOutgoingLinksHostnames"] 
=== Implement a policy to allow outgoing links to specific hosts

Use `allowedOutgoingLinksHostnames` to specify hosts that users can create links to.

. Determine which namespaces you want to apply this policy to.
. Create a CR with `allowedOutgoingLinksHostnames` set to a pattern of allowed hosts.
. Create and apply the CR.

For example, the following CR allows links to all subdomains of `example.com` for all namespaces: 
[source,yaml]
----
apiVersion: skupper.io/v1alpha1
kind: SkupperClusterPolicy
metadata:
  name: allowedOutgoingLinksHostnames
spec:
  namespaces:
    - "*"
  allowedOutgoingLinksHostnames: ['*.example.com']
----


// Type: procedure
[id="allowedServices"] 
=== Implement a policy to allow specific services

Use `allowedServices` to specify which services can be created or used on the {service-network}.

.Procedure

. Determine which namespaces you want to apply this policy to.
. Create a CR with `allowedServices` set to specify the services allowed on the {service-network}.
. Create and apply the CR.

For example, the following CR allows users expose services with the prefix `backend-` for all namespaces: 
[source,yaml]
----
apiVersion: skupper.io/v1alpha1
kind: SkupperClusterPolicy
metadata:
  name: allowedServices
spec:
  namespaces:
    - "*"
  allowedServices: ['backend-*']
----

NOTE: When exposing services, use the `--address <name>` parameter of the `skupper` CLI to name services appropriately.


// Type: procedure
[id="allowedExposedResources"] 
=== Implement a policy to allow specific resources

Use `allowedExposedResources` to specify which service bindings can be created or used on the {service-network}.

.Procedure

. Determine which namespaces you want to apply this policy to.
. Create a CR with `allowedExposedResources` set to specify the service bindings allowed on the {service-network}.
. Create and apply the CR.

For example, the following CR allows users expose services with the prefix `backend-` for all namespaces: 
[source,yaml]
----
apiVersion: skupper.io/v1alpha1
kind: SkupperClusterPolicy
metadata:
  name: allowedExposedResources
spec:
  namespaces:
    - "*"
  allowedExposedResources: ['backend-*']
----

[NOTE] 
====
When binding services, specify an appropriate name when using the `skupper` CLI, for example:
[source,bash]
----
$ skupper service bind backend-db <target-type> <target-name>
----
====