include::{mod-loc}attributes.adoc[]

//Category: skupper-policy
// Type: assembly
[id="skupper-policy"] 
= Securing a {service-network}

By default, {skupper-name} includes many security features.
If you apply the {policy-system}, all communication is denied, and you can specify granular policies to allow your {service-network} operate.

{skupper-name} provides default, built-in security that scales across clusters and clouds. 
In a {service-network}, the communication between sites is performed by {skupper-router}s and is secured with mutual TLS using a private, dedicated certificate authority (CA). 
Each {skupper-router} is uniquely identified by its own certificate.
This means that the {service-network} is isolated from external access, preventing security risks such as lateral attacks, malware infestations, and data exfiltration.


// Type: concept
[id="about-skupper-policies"] 
== About the {policy-system}

After installing the {policy-system} Custom Resource Definition (CRD), you need to configure one or more of the following items using custom resources (CRs) to enable communication:

Allow incoming links:: Use `AllowIncomingLinks` to enable users create tokens and configure incoming links.

Allow outgoing links to specific hosts:: Use `allowedOutgoingLinksHostnames` to specify hosts that users can create links to.

Allow services:: Use `allowedServices` to specify which services can be created or used on the {service-network}.

Allow resources to be exposed:: Use `allowedExposedResources` to specify which service bindings can be created or used on the {service-network}.

NOTE: Each setting for the {policy-system} can be applied to one or more namespaces.

For example, the following policy CR disallows outgoing links for all namespaces, but all other {skupper-name} capabilities are allowed:

[source,yaml]
----
apiVersion: skupper.io/v1alpha1
kind: SkupperClusterPolicy
metadata:
  name: cluster-policy-sample-01
spec:
  namespaces:
    - "*"
  allowIncomingLinks: true
  allowGateway: true
  allowedExposedResources:
    - "*"
  allowedOutgoingLinksHostnames: []
  allowedServices:
    - "*"
----

`namespaces`:: One or more patterns to specify the namespaces that this policy applies to.

`allowIncomingLinks`:: Specify `true` or `false` to determine whether other sites can create links to the namespaces specified.

`allowedOutgoingLinksHostnames`:: Specify one or more patterns to determine which hosts you can create links to from the namespaces specified.

`allowedServices`:: Specify one or more patterns to determine the permitted names of services allowed on the {service-network} from the namespaces specified.

`allowedExposedResources`:: Specify one or more patterns to determine the permitted names of service bindings allowed on the {service-network} from the namespaces specified.

[TIP]
====
The following patterns are valid:

`*`:: Applies to all.

Regular expressions:: Any valid regular expression, for example `.*/.com` will match any string ending in `.com`.

====

If you create another CR that allows outgoing links for a specific namespace, a user can create a link from that namespace to join a {service-network}, that is, the logic for multiple policy CRs is `OR`.
{skupper-name} allows operations if one or more of the policy CRs permits the operation.

== Installing the {policy-system} CRD

Install the {policy-system} CRD enables a cluster administrator enforce policies for {service-network}s.

.Prerequisites

* Access to a cluster using a `cluster-admin` account

.Procedure

. Log into the cluster using a `cluster-admin` account.

. Download the CRD.

. Apply the CRD:
+
[source,yaml]
----
$ kubectl apply -f skupper_cluster_policy_crd.yaml

customresourcedefinition.apiextensions.k8s.io/skupperclusterpolicies.skupper.io created
clusterrole.rbac.authorization.k8s.io/skupper-service-controller created
----

// to be modified soon
. Create a rolebinding in all namespaces.

. To verify that the {policy-system} is active, use the `skupper status` command and check that the output includes the following line:
+
----
Skupper policy is enabled
----

