ifndef::mod-loc[]
:mod-loc: ./partials/
endif::mod-loc[]
include::{mod-loc}attributes.adoc[]
:sectnums:
//Category: k8s-tutorial
// Type: assembly
[id="k8s-tutorial"] 
= Creating a {service-network} with Kubernetes

[role="system:abstract"]
This tutorial demonstrates how to connect a frontend service on a {kubernetes-flavor} cluster with a backend service on a {kubernetes-flavor} cluster using the `skupper` command-line interface (CLI).

See {SkupperOverviewBookLink} for an introduction to {skupper-name}.

.Prerequisites

* Access to namespaces in two {kubernetes-flavor} clusters, `cluster-admin` access is not required.
* One of the {kubernetes-flavor} clusters must be addressable from the other cluster.
* `kubectl` CLI. Many commands can be performed on OpenShift using `oc`, however this tutorial shows the `kubectl` options.

This tutorial shows how to connect the following namespaces:

* `west` - runs the frontend service and is typically a public cluster.
* `east` - runs the backend service.

//include::cli/pages/installing.adoc[leveloffset=+1]


// Type: procedure
[id="configuring-consoles"] 
== Configuring terminal sessions

[role="system:abstract"]
This procedure describes how to configure your terminal sessions to use configurations to avoid problems as you configure {skupper-name} on different clusters.

The following table shows how you might set up your terminal sessions.

.Terminal sessions
[cols="1,1"]
|===
|west terminal session  |east terminal session

a|
[source,bash,subs="attributes+"]
----
 $ kubectl get pods
----
a|
[source,bash,subs="attributes+"]
----
 $ kubectl get pods

----


|===

.Procedure

. Start a terminal session to work on the `west` namespace and set the `KUBECONFIG` environment variable:
+
[source,bash]
----
$ export KUBECONFIG=$HOME/.kube/config-west
----
+
This session is referred to later as the _west_ terminal session.

. Start a terminal session to work on the `east` namespace and set the `KUBECONFIG` environment variable:
+
[source,bash]
----
$ export KUBECONFIG=$HOME/.kube/config-east
----
+
This session is referred to later as the _east_ terminal session.

. In each terminal session, log into the {kubernetes-flavor} cluster.

// Type: procedure
[id="installing-skupper"] 
== Installing the {service-network} router in both clusters


. In the west terminal session:

.. Create the `west` namespace:
+
[source,bash]
----
$ kubectl create namespace west
$ kubectl config set-context --current --namespace west
----

.. Create the {service-network} router:
+
[source,bash]
----
$ skupper init
----

.. Check the site status:
+
--
[source,bash]
----
$ skupper status
----
The output should be similar to the following:
----
Skupper enabled for namespace 'west'. It is not connected to any other sites.
----
--


. In the east terminal session:
.. Create the `east` namespace:
+
[source,bash]
----
$ kubectl create namespace east
$ kubectl config set-context --current --namespace east
----

.. Create the {service-network} router:
+
[source,bash]
----
$ skupper init
----

.. Check the site status:
+
--
[source,bash]
----
$ skupper status
----
The output should be similar to the following:
----
Skupper enabled for namespace 'east'. It is not connected to any other sites.
----
--

// Type: procedure
[id="connecting-namespaces"] 
== Connecting namespaces to create a {service-network}

With the {service-network} routers installed, you can connect them together securely and allow service sharing across the {service-network}.

.Procedure

. In the west terminal session, create a connection token to allow connection to the west namespace:
+
[source,bash]
----
$ skupper token create $HOME/secret.yaml
----
+
This command creates the `secret.yaml` file in your home directory, which you can use to create the secure connection.

. In the east terminal session, use the token to create a connection to the west namespace:
+
[source,bash]
----
$ skupper link create $HOME/secret.yaml
----

. Check the site status from the west terminal session:
+
--
[source,bash]
----
$ skupper status
----
The output should be similar to the following:
----
Skupper is enabled for namespace "west" in interior mode. It is connected to 1 other site. It has no exposed services.
The site console url is:  https://<skupper-url>
The credentials for internal console-auth mode are held in secret: 'skupper-console-users'
----
--

// Type: procedure
[id="frontend"] 
== Creating the frontend service

The frontend service is a simple Python application that displays a message from the backend application.

.Procedure

Perform all tasks in the west terminal session:

. Deploy the frontend service:
+
[source,bash]
----
$ kubectl create deployment hello-world-frontend --image quay.io/skupper/hello-world-frontend
----

. Expose the frontend deployment as a cluster service:
+
[source,bash]
----
$ kubectl expose deployment hello-world-frontend --port 8080 --type LoadBalancer
----

. Check the frontend route:
.. Get the route details:
+
--
[source,bash]
----
$  kubectl get service/frontend
----

The output should be similar to the following:

----
NAME                   HOST/PORT                                   
NAME       TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)          AGE
frontend   LoadBalancer   10.103.232.28   <external-ip>   8080:30407/TCP   15s
----
--

.. Navigate to the `<frontend-ip>:8080` URL in your browser, you see a message similar to the following because the frontend cannot communicate with the backend yet:
+
----
Trouble! HTTPConnectionPool(host='hello-world-backend', port=8080): Max retries exceeded with url: /api/hello (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbfcdf0d1d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
----
+
To resolve this situation, you must create the backend service and make it available on the {service-network}.

// Type: procedure
[id="backend"] 
== Creating the backend service and making it available on the {service-network}

The backend service runs in the `east` namespace and is not available on the {service-network} by default.
You use the `skupper` command to expose the service to all namespaces on the {service-network}.
The backend app is a simple Python application that passes a message to the frontend application.

.Procedure

. Deploy the backend service in the east terminal session:
+
[source,bash]
----
$ kubectl create deployment hello-world-backend --image quay.io/skupper/hello-world-backend
----

. Expose the backend service on the {service-network} from the east terminal session:
+
[source,bash]
----
$ skupper expose deployment hello-world-backend --port 8080 --protocol tcp
----

. Check the site status from the west terminal session:
+
--
[source,bash]
----
$ skupper status
----
The output should be similar to the following:
----
Skupper is enabled for namespace "west" in interior mode. It is connected to 1 other site. It has 1 exposed service.
----
The service is exposed from the `east` namespace.
--

. Check the frontend route in the west terminal session:

.. Get the route details:
+
--
[source,bash]
----
$  oc get routes
----

The output should be similar to the following:

----
NAME                   HOST/PORT                                   
hello-world-frontend   <frontend-url>       
----
--

.. Navigate to the `<frontend-url>` value in your browser, you see a message similar to the following:
+
----
Hi, <name>. I am Mathematical Machine (backend-77f8f45fc8-mnrdp).
----
+
If you click *Say hello* again, a different backend process responds showing how {skupper-name} balances the requests.


This shows how the frontend calls the backend service over the {service-network} from a different {kubernetes-flavor} cluster.

.Additional resources

* {SkupperConsoleBookLink}
* {SkupperCliBookLink}

// Type: procedure
[id="tearing-down"] 
== Tearing down the {service-network}

This procedure describes how to remove the {service-network} you created.

. Delete the `west` namespace from the west terminal session:
+
[source,bash]
----
$ kubectl delete namespace west
----


. Delete the `east` namespace from the east terminal session:
+
[source,bash]
----
$ kubectl delete namespace east
----



