// Type: assembly
[id="encrypting-traffic-pod-router"] 
= Encrypting traffic from a pod to the Skupper router

This section describes how to apply certificates to encrypt the traffic within a cluster.

By default:

* {Skupper-name} creates certificates to establish links between sites using mutual TLS.
This ensures that traffic between sites is encrypted. To use custom certificates for traffic between sites, see xref:index.adoc[].

* Network traffic between pods and the Skupper router is not encrypted. 

You can use certificates to encrypt traffic between pods and the Skupper router as follows:

* xref:skupper-generated-certs[] - does not require user to provide certificates.
* xref:user-provided-certs[] - requires that the certificate authority, and the signed certificates, are distributed across all sites.

NOTE: With both procedures, you reference the certificates when you expose the service on the {service-network}.
If you do not reference certificates, the traffic between pods and the Skupper router is unencrypted.

// Type: procedure
[id="skupper-generated-certs"]
= Exposing services on the {service-network} with Skupper-generated certificates

A {skupper-name} installation includes a certificate authority which can generate certificates that can be used to encrypt traffic from the pod to the Skupper router.
This procedure describes how to use those certificates in your {service-network}.

.Prerequisites

* Access to Kubernetes site where the service is exposed
* Access to Kubernetes site where the service is called from
* service sync is enabled on both sites

.Procedure

. Expose the service on the {service-network}:

.. If you use the `expose` option:
+
--
----
$ skupper expose  <target-type> <target-name> --generate-tls-secrets
----
For example, to expose a `backend` deployment using `http2`:
----
$ skupper expose deployment backend --port 8080 --protocol http2 --generate-tls-secrets
----
--

.. If you use `create` and `bind` options:
+
--
----
$ skupper service create <service-name> --generate-tls-secrets
$ skupper service bind <service-name>  <target-type> <target-name>
----
--

. Check that the service is available on another site:
+
--
----
$ skupper service status
Services exposed through Skupper:
╰─ nghttp2tls (http2 port 443)
----

On this site, a secret is created named `skupper-tls-<service-name>`. 
The secret contains the generated certificates under `data/ca.crt`, `data/tls.crt` and `data/tls.key`.
--

. Configure components that call the exposed service to use the certificates stored in `skupper-tls-<service-name>`.
+
--
For example, modify a deployment to mount the secret in a container.

----
      volumes:
      - name: certs
        secret:
          secretName: skupper-tls-nghttp2tls
----
--

. Configure the exposed service, that is the component that responds to the request, to use the certificates stored in `skupper-service-client`.
+
--
For example, modify a deployment to mount the secret in a container.

----
      volumes:
      - name: certs
        secret:
          secretName: skupper-service-client
----
--


// Type: procedure
[id="user-provided-certs"] 
= Exposing services on the {service-network} with user-provided certificates

You can encrypt traffic from the pod to the Skupper router using certificates provided by a certificate authority.

.Prerequisites

* Access to Kubernetes site where the service is exposed
* Access to Kubernetes site where the service is called from
* Certificate authority access (intermediate certificate is sufficient)


.Procedure

. Create a secret from the certificate authority, for example:
+
--
----
$ kubectl create secret tls ca-tls-secret --key=rootCA.key.pem --cert=rootCA.crt.pem
----
--


. Create secrets from the certificate and private key files:
+
--
----
$ kubectl create secret tls user-tls-<service-name> --key <key-path> --cert <cert-path>
----

For example

----
kubectl create secret tls user-tls-nghttp2tls --key ./tls.key --cert ./tls.crt
----
--

. Expose the service on the {service-network}:

.. If you use the `expose` option, you specify both certificate secret and the public CA secret, for example:
+
----
$ skupper expose deployment backend --port 5432 --protocol http2 --tls-cert user-tls-nghttp2tls --tls-trust ca-tls-secret
----

.. If you use the `create` and `bind` options:
+
--
----
$ skupper service create backend 5432 --tls-cert user-tls-nghttp2tls
$ skupper bind deployment backend  --port 5001  --protocol http2 --tls-trust ca-tls-secret
----
--
