// Type: assembly
[id="custom-certs"] 
= Exposing services on the {service-network} using custom certificates

By default, {skupper-name} creates certificates to establish links between sites using mutual TLS.
If you want to use custom certificates to protect the communication from component to component, you can use certificates as follows:

* xref:skupper-generated-certs[]
* xref:provided-certs[]

// Type: procedure
[id="skupper-generated-certs"] 
= Exposing services on the {service-network} using generated certificates

You can protect component to component communication on the {service-network} using certificates generated by {skupper-name}.

.Prerequisites

* Access to Kubernetes site where the service is exposed
* Access to Kubernetes site where the service is called from
* service sync is enabled on both sites



.Procedure

. Expose the service on the {service-network}:

.. If you use the `expose` option:
+
--
----
$ skupper expose  <target-type> <target-name> --generate-tls-secrets
----
For example, to expose a `backend` deployment using `http2`:
----
$ skupper expose deployment backend --port 8080 --protocol http2 --generate-tls-secrets
----
--

.. If you use `create` and `bind` options:
+
--
----
$ skupper service create <service-name> --generate-tls-secrets
$ skupper service bind <service-name>  <target-type> <target-name>
----
--

. Check that the service is available on another site:
+
--
----
$ skupper service status
Services exposed through Skupper:
╰─ nghttp2tls (http2 port 443)
----

On this site, a secret is created to support client usage:

skupper-tls-<service-name>:: contains the generated certificates under `data/ca.crt`, `data/tls.crt` and `data/tls.key`.
--

. Configure components that call the exposed service to use the certificates. 
+
--
For example, modify a deployment to mount the secret in a container.

----
      volumes:
      - name: certs
        secret:
          secretName: skupper-tls-nghttp2tls
----

--


// Type: procedure
[id="provided-certs"] 
= Exposing services on the {service-network} using provided certificates

You can protect component to component communication on the {service-network} using certificates provided by a certificate authority.

.Prerequisites

* Access to Kubernetes site where the service is exposed
* Access to Kubernetes site where the service is called from
* Certificate and private key files. Assuming `tls.crt` and `tls.key` filenames.


.Procedure

. Create secrets from the certificate and private key files:
+
--
----
$ kubectl create secret tls skupper-tls-<service-name>\
--key <key-pat> \
--cert <cert-path>
----

For example

----
kubectl create secret tls skupper-tls-nghttp2tls --key ./tls.key --cert ./tls.crt
----
--

. Create a secret from the certificate authority public key:
+
--
----
$ kubectl create secret tls public-ca --key ./ca.key.pub --cert ./ca.crt
----

--

. Expose the service on the {service-network}:

.. If you use the `expose` option, you specify both certificate secret and the public CA secret, for example:
+
----
$ skupper expose deployment backend --port 5432 --protocol http2 --tls-cert backend-secret --tls-trust public-ca-secret
----

.. If you use the `create` and `bind` options:
+
--

----
$ skupper service create backend 5432 --tls-cert backend-secret
$ skupper bind deployment backend  --port 5001  --protocol http2 --tls-trust public-ca-secret
----


--
