// Type: procedure
[id='installing-operator-using-cli']
== Installing the Operator using the CLI


The steps in this section show how to use the `kubectl` command-line interface (CLI) to install and deploy the latest version of the {SkupperOperatorName} in a given Kubernetes cluster.

.Prerequisites

* The Operator Lifecycle Manager is installed in the cluster.
For more information, see the link:https://olm.operatorframework.io/docs/getting-started/[QuickStart].

.Procedure

. Download the Skupper Operator example files, for example:
+
----
$ wget https://github.com/skupperproject/skupper-operator/archive/refs/heads/main.zip
----

. Create a `my-namespace` namespace.
NOTE: If you want to use a different namespace, you need to edit the referenced YAML files.

.. Create a new namespace:
+
[source,bash,options="nowrap",subs="+quotes"]
----
$ kubectl create namespace my-namespace
----

.. Switch context to the namespace:
+
[source,bash,options="nowrap",subs="+quotes"]
----
$ kubectl config set-context --current --namespace=my-namespace
----

. Create a CatalogSource in the `openshift-marketplace` namespace:
+
[source,bash,options="nowrap",subs=attributes+]
----
$ kubectl apply -f examples/k8s/00-cs.yaml
----

. Verify the skupper-operator catalog pod is running before continuing:
+
[source,bash,options="nowrap",subs=attributes+]
----
$ kubectl -n olm get pods | grep skupper-operator
----

. Create an OperatorGroup in the `my-namespace` namespace:
+
[source,bash,options="nowrap",subs=attributes+]
----
$ kubectl apply -f examples/k8s/10-og.yaml
----

. Create a Subscription  in the `my-namespace` namespace:
+
[source,bash,options="nowrap",subs=attributes+]
----
$ kubectl apply -f examples/k8s/20-sub.yaml
----

. Verify that the Operator is running:
+
[source,bash,options="nowrap"]
----
$ kubectl get pods -n my-namespace

NAME                                     READY   STATUS    RESTARTS   AGE
skupper-site-controller-d7b57964-gxms6   1/1     Running   0          1m
----
+
If the output does not report the pod is running, use the following command to determine the issue that prevented it from running:
+
----
$ kubectl describe pod -l name=skupper-operator
----
