"""
Parser for cli-doc markdown files generated by Cobra.
Extracts command information from the markdown format.
"""

import re
from common import *

def parse_cli_doc(filepath):
    """
    Parse a cli-doc markdown file and extract command information.
    
    Returns a dict with:
    - name: command name (e.g., "site create")
    - title: display title
    - synopsis: command description
    - usage: usage syntax
    - options: list of option dicts
    - inherited_options: list of inherited option dicts
    - examples: list of example strings
    - see_also: list of related command links
    """
    content = read(filepath)
    
    command_info = {
        "name": extract_command_name(content),
        "title": extract_title(content),
        "synopsis": extract_synopsis(content),
        "usage": extract_usage(content),
        "options": extract_options(content, "### Options"),
        "inherited_options": extract_options(content, "### Options inherited from parent commands"),
        "examples": extract_examples(content),
        "see_also": extract_see_also(content),
    }
    
    return command_info

def extract_command_name(content):
    """Extract command name from title (e.g., 'skupper site create' -> 'site create')"""
    lines = content.split('\n')
    for line in lines:
        if line.startswith('## skupper '):
            # Remove '## skupper ' prefix
            full_name = line[11:].strip()
            return full_name
    return None

def extract_title(content):
    """Extract the display title"""
    lines = content.split('\n')
    for line in lines:
        if line.startswith('## skupper '):
            return line[3:].strip()  # Remove '## '
    return None

def extract_synopsis(content):
    """Extract the synopsis/description section"""
    lines = content.split('\n')
    synopsis_lines = []
    in_synopsis = False
    
    for line in lines:
        if line.startswith('### Synopsis'):
            in_synopsis = True
            continue
        if in_synopsis:
            if line.startswith('```') or line.startswith('###'):
                break
            if line.strip():
                synopsis_lines.append(line)
    
    return '\n'.join(synopsis_lines).strip()

def extract_usage(content):
    """Extract the usage syntax from the code block after Synopsis"""
    lines = content.split('\n')
    in_synopsis = False
    in_code_block = False
    usage_lines = []
    
    for line in lines:
        if line.startswith('### Synopsis'):
            in_synopsis = True
            continue
        if in_synopsis and line.strip() == '```':
            if not in_code_block:
                in_code_block = True
                continue
            else:
                # End of code block
                break
        if in_code_block:
            usage_lines.append(line)
    
    return '\n'.join(usage_lines).strip()

def extract_options(content, section_header):
    """
    Extract options from a section (either main options or inherited options).
    
    Returns list of dicts with:
    - name: flag name (without --)
    - description: flag description
    - type: inferred type (string, boolean, duration, etc.)
    - default: default value if specified
    - choices: list of choices if specified
    """
    lines = content.split('\n')
    options = []
    in_section = False
    current_option = None
    
    for line in lines:
        if line.startswith(section_header):
            in_section = True
            continue
        
        if in_section and line.startswith('###'):
            # End of section
            break
        
        if not in_section:
            continue
        
        # Check if this is a new option line (starts with whitespace and --)
        if line.strip().startswith('--') or line.strip().startswith('-h,'):
            # Save previous option if exists
            if current_option:
                options.append(current_option)
            
            # Parse new option
            current_option = parse_option_line(line)
        
        elif current_option and line.strip():
            # Continuation of description
            if 'description' in current_option:
                current_option['description'] += ' ' + line.strip()
            else:
                current_option['description'] = line.strip()
    
    # Don't forget the last option
    if current_option:
        options.append(current_option)
    
    # Post-process descriptions to extract additional info
    for option in options:
        post_process_option(option)
    
    return options

def parse_option_line(line):
    """
    Parse a single option line.
    Examples:
    '      --enable-ha                 Configure the site for high availability'
    '  -h, --help                      help for create'
    '      --link-access-type string   configure external access'
    '      --timeout duration          raise an error (default 3m0s)'
    """
    option = {}
    
    # Remove leading whitespace
    line = line.strip()
    
    # Split on first whitespace after flag(s)
    parts = re.split(r'\s{2,}', line, maxsplit=1)
    
    if len(parts) < 1:
        return option
    
    flag_part = parts[0]
    desc_part = parts[1] if len(parts) > 1 else ""
    
    # Extract flag name (handle both -h, --help and --flag formats)
    if ', --' in flag_part:
        # Format: -h, --help
        long_flag = flag_part.split(', --')[1].split()[0]
        option['name'] = long_flag
    elif flag_part.startswith('--'):
        # Format: --flag or --flag type
        flag_parts = flag_part.split()
        option['name'] = flag_parts[0][2:]  # Remove --
        
        # Check for type
        if len(flag_parts) > 1:
            option['type'] = flag_parts[1]
    elif flag_part.startswith('-'):
        # Short flag only (like -h)
        option['name'] = flag_part[1:]
    
    # Store initial description
    if desc_part:
        option['description'] = desc_part
    
    return option

def post_process_option(option):
    """Extract additional information from description"""
    if 'description' not in option:
        return
    
    desc = option['description']
    
    # Extract default value
    default_match = re.search(r'\(default[:\s]+([^)]+)\)', desc)
    if default_match:
        option['default'] = default_match.group(1).strip()
    
    # Extract choices
    choices_match = re.search(r'Choices:\s*\[([^\]]+)\]', desc)
    if choices_match:
        choices_str = choices_match.group(1)
        option['choices'] = [c.strip() for c in choices_str.split('|')]
    
    # Infer type if not already set
    if 'type' not in option:
        if 'duration' in desc.lower() or option.get('default', '').endswith('s') or option.get('default', '').endswith('m'):
            option['type'] = 'duration'
        elif option.get('default') in ['true', 'false']:
            option['type'] = 'boolean'
        elif 'choices' in option:
            option['type'] = 'string'
        elif any(word in desc.lower() for word in ['enable', 'disable']) and 'type' not in option:
            option['type'] = 'boolean'
        else:
            # Default to boolean for flags without explicit type
            option['type'] = 'boolean'

def extract_examples(content):
    """Extract examples from the Examples section"""
    lines = content.split('\n')
    examples = []
    in_examples = False
    in_code_block = False
    current_example = []
    
    for line in lines:
        if line.startswith('### Examples'):
            in_examples = True
            continue
        
        if in_examples and line.startswith('###'):
            # End of examples section
            break
        
        if not in_examples:
            continue
        
        if line.strip() == '```':
            if not in_code_block:
                in_code_block = True
                current_example = []
            else:
                # End of code block
                in_code_block = False
                if current_example:
                    examples.append('\n'.join(current_example).strip())
            continue
        
        if in_code_block:
            current_example.append(line)
    
    return examples

def extract_see_also(content):
    """Extract related commands from SEE ALSO section"""
    lines = content.split('\n')
    see_also = []
    in_section = False
    
    for line in lines:
        if line.startswith('### SEE ALSO'):
            in_section = True
            continue
        
        if in_section and line.startswith('#'):
            # End of section
            break
        
        if not in_section:
            continue
        
        # Parse markdown link: * [skupper site](skupper_site.md)
        link_match = re.match(r'\*\s+\[([^\]]+)\]\(([^)]+)\)', line.strip())
        if link_match:
            title = link_match.group(1)
            href = link_match.group(2)
            see_also.append({
                'title': title,
                'href': href,
            })
    
    return see_also

def parse_all_cli_docs(cli_doc_dir="cli-doc"):
    """
    Parse all cli-doc markdown files in a directory.
    
    Returns a dict mapping command names to command info.
    """
    commands = {}
    
    for filename in list_dir(cli_doc_dir):
        if not filename.endswith('.md'):
            continue
        
        filepath = join(cli_doc_dir, filename)
        
        try:
            command_info = parse_cli_doc(filepath)
            if command_info['name']:
                commands[command_info['name']] = command_info
                debug(f"Parsed {filename}: {command_info['name']}")
        except Exception as e:
            warning(f"Failed to parse {filename}: {e}")
    
    return commands

# For testing
if __name__ == "__main__":
    import sys
    
    if len(sys.argv) > 1:
        # Parse specific file
        filepath = sys.argv[1]
        info = parse_cli_doc(filepath)
        
        print(f"Command: {info['name']}")
        print(f"Title: {info['title']}")
        print(f"\nSynopsis:\n{info['synopsis']}")
        print(f"\nUsage:\n{info['usage']}")
        print(f"\nOptions ({len(info['options'])}):")
        for opt in info['options']:
            print(f"  --{opt['name']}: {opt.get('description', '')[:60]}...")
        print(f"\nExamples ({len(info['examples'])}):")
        for ex in info['examples']:
            print(f"  {ex[:60]}...")
    else:
        # Parse all
        commands = parse_all_cli_docs()
        print(f"Parsed {len(commands)} commands")
        for name in sorted(commands.keys()):
            print(f"  - {name}")

# Made with Bob
