include::../partials/attributes.adoc[]
// Type: concept
[id="understanding-tls"] 
= Understanding TLS certificates for Kubernetes sites

The traffic between sites is encrypted using mutual TLS providing secure communication between Kubernetes clusters.
If you do not provide certificates as described in this section, certificates are generated to create the mutual TLS connection.
The traffic between components within the site is also encrypted using mutual TLS.

{skupper-name} supports end-to-end encryption of your application traffic, however you might want to avoid encrypt traffic from client to router and then from router to server as described in xref:tls-router-app[]

In TLS, two key checks occur during the handshake establishing the connection:

Trust of the peer’s certificate:: The certificate must be validated against a list of trusted Certificate Authorities (CAs). 
If the certificate is signed by a trusted CA and the certificate chain is valid, the peer’s certificate is trusted.

Identity match:: The peer’s identity (for example, domain name) must match the Common Name (CN) or Subject Alternative Names (SANs) in the certificate. 
If there is a mismatch, the connection is considered insecure.

Both conditions must be met for the connection to be established.

This section describes the Kubernetes Secrets involved for various scenarios so that you can populate those Secrets using custom certificates if required.

== Overview

By default, {skupper-name} creates Secrets to support TLS for the following traffic:

(1) Within a site:: Traffic flowing between a router and the service controller.

(2) Between sites:: Traffic flowing between routers, including between routers in different sites.


When running in Kubernetes, {skupper-name} expects specific Secrets that support TLS for each of the above scenarios in each namespace where it is installed. 
These Secrets, which contain TLS keys and certificates for each of the scenarios above, are assigned predefined names.

When you create a site using the CLI or create a site declaratively using YAML, {skupper-name} creates the required Secrets if they do not already exist.

If you use your certificates to populate the Secrets before the site is created, {skupper-name} uses those certificates. 

[NOTE]
====
CA Secrets always have a name with the suffix `-ca`.
For every scenario above, there is a Secret with the *-ca* suffix which are only used if the associated Secrets do not already exist.
For example:

* The `skupper-local-ca` Secret is only used if the `skupper-local-client` and `skupper-local-server` Secrets do not exist.
* The `skupper-site-ca` Secret is only used if the `skupper-site-server` Secret does not exist. 

// Possible update would be to link to article outlining 'replacing CAs'
====

TIP: See your provider documentation for generating certificates. For example, link:https://docs.openshift.com/container-platform/4.17/security/cert_manager_operator/`cert-manager-creating`-certificate.html#`cert-manager-certificate`-mgmt_cert-`manager-creating-certificate`[Creating certificates for user workloads] if you use `cert-manager` on OpenShift.

== (1) Mutual TLS within a site

Within a {skupper-name} site, the service controller pod needs to connect to the skupper router. 
This connection is secured using mutual TLS, and the required keys and certificates are stored in specific Secrets, all sharing the prefix *skupper-local-*:

`skupper-local-client`:: Contains the key and certificate for the service controller, along with a list of trusted certificates used for verifying peer certificates.
`skupper-local-server`:: Contains the key and certificate for the router, along with a list of trusted certificates used for verifying peer certificates.

If these Secrets do not exist, {skupper-name} creates them using a self-signed certificate generated by {skupper-name} when the site is created and stored in the `skupper-local-ca` Secret.

NOTE: {skupper-name} only uses this Secret if `skupper-local-server` and `skupper-local-client` are not populated.

== (2) Mutual TLS between sites

When two sites are linked, the routers communicate using mutual TLS and the required keys and certificates are stored in specific Secrets:

`skupper-site-server`:: Contains the key, certificate, and the CA certificate used by the `skupper-router` when accepting links from other sites.
`<link-specific-name>`:: Contains the key, certificate, and the CA certificate used by the `skupper-router` when creating links to other sites.

To establish a link, both routers must verify the following:

* The peer's certificate was signed by a trusted CA.
* The certificate of the peer matches the hostname or IP address used to establish the link.

If these Secrets do not exist, {skupper-name} creates them using a certificate authority (CA) to sign the certificates. 

For this purpose, {skupper-name} generates another Secret:

`skupper-site-ca`:: Contains a key and a self-signed certificate. 


NOTE: {skupper-name} only uses this Secret if `skupper-site-server` is not populated.


include::app-tls.adoc[leveloffset=+1]

== Summary of TLS related Secrets

[cols=5*]
|===

| Scenario | Secret Name | Components | Category | Notes 

| (1) Mutual TLS within a site 
| `skupper-local-ca` 
| core 
| Certificate authority for signing `skupper-local-client` and `skupper-local-server` Secrets. 
| Created by default. Not used if user provides other Secrets. 

|  
| `skupper-local-client` 
| `skupper-service-controller`, `skupper-flow-collector` 
| Secures connections to the `skupper-router` using mutual TLS. 
| The flow collector is an optional component, required for console.

|  
| `skupper-local-server` 
| `skupper-router` 
| Secures incoming connections from `skupper-service-controller` and `skupper-flow-collector`. 
| The flow collector is an optional component, required for console 


| (2) Mutual TLS between {skupper-name} Sites 
| `skupper-site-ca` 
| core 
| CA for signing certificates in `skupper-site-server` and client certificates for links. 
|  Created by default. Not used if user provides other Secrets. 

|  
| `skupper-site-server` 
| `$1` 
| Secures incoming connections from other {skupper-name} sites. | Contains key, certificate, and CA certificate. 

|
| `<link-specific-Secret>` 
| `skupper-router` 
| Used by the initiating site's router to establish a link with another {skupper-name} site. 
| Labeled with `skupper.io/type=connection-token`

| (3) TLS between {skupper-name} Router and Applications | `skupper-service-ca` 
| {skupper-name} router, external services 
| Manages CA certificates for TLS termination and connections. 
| Created by default. Not used if user provides other Secrets. 
|

|  
| `skupper-service-client` 
| {skupper-name} router, external services 
| Secures TLS termination at the router and TLS connections to services. 
| Users can provide their own Secrets via \--tls-cert and annotations.

|===
