include::../partials/attributes.adoc[]
// Type: concept
[id="understanding-ingress"] 
= Understanding ingress

When you create a site that can be linked to, you need to enable ingress on that site.
By default, ingress is enabled, however you can disable it or set it to use a specific ingress type.

By default, the ingress type is set to:

* `route` if available (OpenShift)
* `loadbalancer`

Other options include:

* `none` useful if you do not need to link to the current site.
* `nodeport`
* `nginx-ingress-v1`
* `contour-http-proxy`

You can set the ingress type using the CLI when creating the site `skupper init --ingress <type>` or by setting the type in your site YAML, for example to disable ingress:

[source, bash]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: skupper-site
data:
  name: my-site
  ingress: "none"
----

If the default ingress is not suitable, an alternative is `nginx-ingress-v1`.
Nginx uses Server Name Indication (SNI) to identify connection targets, which eliminates the need for assigning separate IP addresses as required by `loadbalancer`.

NOTE: When using `nginx-ingress-v1` you must enable SSL Passthrough as described in link:https://kubernetes.github.io/ingress-nginx/user-guide/tls/#ssl-passthrough[Ingress-Nginx Controller documentation].
