// Type: reference
[id="service-sync"] 
= Service synchronization

By default, creating a site enables that site to synchronize all services from other default sites.
This means that all services exposed on the service network are available in the current site.
For example, if you expose the backend service in the `east` site, that service is automatically created in the `west` site. 

However, if you want more granular control over which services are available, you can disable `service-sync`.
This might be required if:

* You expose many services and not all are required on all sites.
* You are concerned that a specific service is not available on a specific site.

To disable service synchronization:

[source, bash, subs=attributes+]
----
$ skupper init --service-sync false
----

or use the following YAML:

[source, yaml, subs=attributes+]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: skupper-site
data:
  name: my-site
  service-sync: false
----

To check whether synchronization is enabled, check the value for `service-sync` in the output from the following command:

[source, bash, subs=attributes+]
----
$ kubectl get cm skupper-site -o json 
----

If you disable service-sync and you want to consume an exposed service on a specific site, you can create that service using the following command:

[source, bash, subs=attributes+]
----
skupper service create <name> <port>
----

where `<name>` is the service name on the site where the service is exposed
and `<port>` is the port used to expose that service.


Notes:

* When considering whether services are synchronized between two sites, `service-sync` must be enabled on both sites.
* If you use the command `skupper service delete` on a site, that command only works if the service was created on that site.
* Podman sites do not support `service-sync`.

