include::../partials/attributes.adoc[]
[id="metrics"] 
= Flow metrics

The following metrics are available to a Prometheus instance when you enable the flow collector using `skupper init --enable-flow-collector`

flows_total:: For tcp protocol this is the total number of connections. 
For http or http2 protocol this is the total number of distinct requests made.

octets_total:: The total number of bytes processed by the router.

active_flows:: The number of flows currently active including open tcp connections and _in flight_ http requests.

address_last_time_seconds:: The time since a flow was last observed in seconds.

flow_latency_microseconds:: The latency in microseconds, as observed by the first and last router involved in the flow.

http_requests_method_total:: Total number of http requests grouped by method.
+
Additional label: The http method, for example, `GET`, `HEAD`, `POST`.

http_requests_result_total:: Total number of http requests by response code.
+
Additional label: The http response code, for example `200`, `403`, `503`.

The following labels are common to these metrics allowing you to filter and categorize the data:

address:: The address relating to the metric.
Typically, this is the service name.

sourceSite:: The site where the flow originated for the metric. 
This string is a combination of the site name and the site ID.

destSite:: The site where the flow terminated for the metric. 
This string is a combination of the site name and the site ID.

direction:: The direction of flow.
For traffic sent from a client to server the value is `incoming`.
For traffic sent from a client to server the value is `outgoing`.

protocol:: The protocol used by the flow, `tcp`, `http`, or `http2`.

sourceProcess:: The name of the process originating the flow.

destProcess:: The name of the process receiving the flow.
