include::{mod-loc}attributes.adoc[]

:context: skupper-operator
//Category: skupper-operator
// Type: assembly
= Using the Skupper Operator on {cluster-brand}

[role="system:abstract"]
The {SkupperOperatorName} creates and manages {skupper-name} sites in {cluster-brand}. 

[id='adding-operator-{context}']
== Adding the Skupper Operator to your cluster

The options for installing the Operator are:

* xref:installing-operator-using-cli-{context}[]
* xref:installing-operator-using-olm-{context}[]
 
[NOTE]
====
Installing an Operator requires administrator-level privileges for your {cluster-brand} cluster.
====

[id='installing-operator-using-cli-{context}']
== Installing the Operator using the CLI

:examples-file: skupper-operator-2.0-ocp-install-examples.zip

The steps in this section show how to use the `kubectl` command-line interface (CLI) to install and deploy the latest version of the {SkupperOperatorName} in a given {cluster-brand} cluster.

.Procedure

ifdef::product[]

. In your web browser, navigate to the *Software Downloads* page for link:https://access.redhat.com/jbossnetwork/restricted/listSoftware.html?downloadType=distributions&product=jboss.amq.interconnect[{skupper-name} releases].

. Ensure that the value of the *Version* drop-down list is set to `{RouterVersion}` and the *Releases* tab is selected.

. Next to *AMQ Interconnect 2.0 Operator Installation and Example Files*, click *Download*.
+
Download of the `{examples-file}` compressed archive automatically begins.

. When the download has completed, move the archive to your chosen installation directory. The following example moves the archive to a directory called `~/router/operator`.
+
[source,bash,options="nowrap",subs="+attributes"]
----
$ mkdir ~/router
$ mv {examples-file} ~/router
----

. In your chosen installation directory, extract the contents of the archive. For example:
+
[source,bash,options="nowrap", subs="+attributes"]
----
$ cd ~/router
$ unzip {examples-file}
----

. Switch to the directory that was created when you extracted the archive. For example:
+
[source,bash,options="nowrap", subs="+attributes"]
----
$ cd operator
----


. Log in to {cluster-brand} as a cluster administrator. For example:
+
[source,bash,options="nowrap"]
----
$ kubectl login -u system:admin
----


. Complete the steps described in link:https://access.redhat.com/RegistryAuthentication[Red Hat Container Registry Authentication^].

endif::[]

ifdef::skupper-io[]


. Download the Skupper Operator example files, for example:
+
----
$ curl -fL https://github.com/skupperproject/skupper-operator/archive/refs/heads/main.zip
----


endif::[]


. Specify the namespace in which you want to install the Operator. You can create a new namespace or switch to an existing one.

.. Create a new namespace:
+
[source,bash,options="nowrap",subs="+quotes"]
----
$ kubectl create namespace  __<namespace-name>__
----

.. Or, switch to an existing namespace:
+
[source,bash,options="nowrap",subs="+quotes"]
----
$ kubectl config set-context --current --namespace=__<namespace-name>__
----

. Create a CatalogSource in the `openshift-marketplace` namespace:
+
[source,bash,options="nowrap",subs=attributes+]
----
$ kubectl apply -f examples/{cluster-dir}/00-cs.yaml
----

. Make sure the skupper-operator catalog pod is running before continuing:
+
[source,bash,options="nowrap",subs=attributes+]
----
$ kubectl -n openshift-marketplace get pods | grep skupper-operator
----

. Create an OperatorGroup in the `my-namespace` namespace:
+
[source,bash,options="nowrap",subs=attributes+]
----
$ kubectl apply -f examples/{cluster-dir}/10-og.yaml
----

. Create a Subscription  in the `my-namespace` namespace:
+
[source,bash,options="nowrap",subs=attributes+]
----
$ kubectl apply -f examples/{cluster-dir}/20-sub.yaml
----

. Verify that the Operator is running:
+
[source,bash,options="nowrap"]
----
$ kubectl get pods -n my-namespace

NAME                                     READY   STATUS    RESTARTS   AGE
skupper-site-controller-d7b57964-gxms6   1/1     Running   0          1m
----
+
If the output does not report the pod is running, use the following command to determine the issue that prevented it from running:
+
----
$ kubectl describe pod -l name=skupper-operator
----

.Additional resources
* For an alternative method of installing the {skupper-name} Operator that uses the OperatorHub graphical interface, see xref:installing-operator-using-olm-{context}[].


[id='installing-operator-using-olm-{context}']
== Installing the Skupper Operator using the OpenShift console

The procedures in this section show how to use the OperatorHub to install and deploy the latest version of the {SkupperOperatorName} in a given OpenShift namespace. 

In {cluster-brand} 4.1 and later, the __Operator Lifecycle Manager__ (OLM) helps users install, update, and generally manage the lifecycle of all Operators and their associated services running across their clusters. It is part of the Operator Framework, an open source toolkit designed to manage Kubernetes native applications (Operators) in an effective, automated, and scalable way.

.Prerequisites

* Access to an {cluster-brand} {OpenShiftVersion} cluster using a `cluster-admin` account.

.Procedure

. In the {cluster-brand} web console, navigate to menu:Operators[OperatorHub].

. Choose `{SkupperOperatorName}` from the list of available Operators, and then click btn:[Install].

. On the *Operator Installation* page, two *Installation mode* options are available:
+
* *All namespaces on the cluster*
* *A specific namespace on the cluster*
+
For this example, choose *A specific namespace on the cluster*.

. Select the namespace into which you want to install the Operator, and then click btn:[Install].
+
The *Installed Operators* page appears displaying the status of the Operator installation.

. Verify that the {skupper-name} Operator is displayed and wait until the *Status* changes to *Succeeded*.

. If the installation is not successful, troubleshoot the error:

.. Click `{SkupperOperatorName}` on the *Installed Operators* page.

.. Select the *Subscription* tab and view any failures or errors.

.Additional resources

For more information about installing Operators, see the link:https://docs.openshift.com/container-platform/4.7/operators/user/olm-installing-operators-in-namespace.html[OpenShift Documentation]

[id='creating-site-using-operator-{context}']
== Creating a site using the Skupper Operator


. Create a YAML file defining the ConfigMap of the site you want to create.
For example, create `skupper-site.yaml`:
+
[source,yaml,options="nowrap"]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: skupper-site
  namespace: my-namespace
----
+
This is the equivalent to `skupper init`.
You can later retrieve the console credentials as described in {ConsoleLink} or specify them now by adding the username and optionally the password to `skupper-site.yaml` as follows:
+
[source,yaml,options="nowrap"]
----
data:
  router-mode: interior
  console-user: "admin"
  console-password: "changeme"
----
 
. Apply the YAML to create a ConfigMap named `skupper-site` in the namespace you want to use:
+
[source,bash,options="nowrap"]
----
$ kubectl apply -f skupper-site.yaml
----

. Verify that the site is created by checking that the Skupper router and service controller pods are running:
+
[source,bash,options="nowrap"]
----
$ kubectl get pods

NAME                                          READY   STATUS    RESTARTS   AGE
skupper-router-8c6cc6d76-27562                1/1     Running   0          40s
skupper-service-controller-57cdbb56c5-vc7s2   1/1     Running   0          34s
----
+
NOTE: If you deployed the Operator to a single namespace, an additional site controller pod is also running.