// Type: procedure
[id='installing-operator-using-olm-{context}']
== Installing the Skupper Operator using the OpenShift console

The procedures in this section show how to use the OperatorHub from the OpenShift console to install and deploy the latest version of the {SkupperOperatorName} in a given OpenShift namespace. 


.Prerequisites

* Access to an {kubernetes-flavor} {OpenShiftVersion} cluster using a `cluster-admin` account.

.Procedure

. In the {kubernetes-flavor} web console, navigate to menu:Operators[OperatorHub].

. Choose `{SkupperOperatorName}` from the list of available Operators, and then click btn:[Install].

. On the *Operator Installation* page, two *Installation mode* options are available:
+
* *All namespaces on the cluster*
* *A specific namespace on the cluster*
+
For this example, choose *A specific namespace on the cluster*.

. Select the namespace into which you want to install the Operator, and then click btn:[Install].
+
The *Installed Operators* page appears displaying the status of the Operator installation.

. Verify that the {skupper-name} Operator is displayed and wait until the *Status* changes to *Succeeded*.

. If the installation is not successful, troubleshoot the error:

.. Click `{SkupperOperatorName}` on the *Installed Operators* page.

.. Select the *Subscription* tab and view any failures or errors.

For more information about installing Operators, see the link:https://docs.openshift.com/container-platform/4.7/operators/user/olm-installing-operators-in-namespace.html[OpenShift Documentation]

.Next steps

* xref:creating-site-using-operator-{context}[]