:kubernetes-flavor: OpenShift
:example-directory: ocp

include::{mod-loc}attributes.adoc[]

:context: skupper-operator-openshift
//Category: skupper-operator
// Type: assembly
[id='using-skupper-operator-{context}']
= Using the Skupper Operator on OpenShift

[role="system:abstract"]
The {SkupperOperatorName} creates and manages {skupper-name} sites in {kubernetes-flavor}. 

There are two options when deploying the Skupper Operator:

All namespaces:: 
All Skupper sites created in the cluster share a common *site controller* pod for co-ordination.
A specific namespace::
A site controller pods is created in each namespace that you apply the `site` ConfigMap.
This is equivalent to the `skupper init` as described in {CliLink}.

You can deploy the Skupper Operator using any of the following methods:

* xref:installing-operator-using-cli-{context}[].
* xref:installing-operator-using-olm-{context}[].


[NOTE]
====
Installing an Operator requires administrator-level privileges for your {kubernetes-flavor} cluster.
====

After installing the Operator, you can create a site by deploying a ConfigMap as described in xref:creating-site-using-operator-{context}[]


include::{mod-loc}installing-operator-using-cli-openshift.adoc[]


include::{mod-loc}installing-operator-using-olm.adoc[]


include::{mod-loc}creating-site-using-operator.adoc[]
