[id='installing-operator-using-olm-{context}']
== Installing the Skupper Operator using the OpenShift console

The procedures in this section show how to use the OperatorHub to install and deploy the latest version of the {SkupperOperatorName} in a given OpenShift namespace. 

In {kubernetes-flavor} 4.1 and later, the __Operator Lifecycle Manager__ (OLM) helps users install, update, and generally manage the lifecycle of all Operators and their associated services running across their clusters. It is part of the Operator Framework, an open source toolkit designed to manage Kubernetes native applications (Operators) in an effective, automated, and scalable way.

.Prerequisites

* Access to an {kubernetes-flavor} {OpenShiftVersion} cluster using a `cluster-admin` account.

.Procedure

. In the {kubernetes-flavor} web console, navigate to menu:Operators[OperatorHub].

. Choose `{SkupperOperatorName}` from the list of available Operators, and then click btn:[Install].

. On the *Operator Installation* page, two *Installation mode* options are available:
+
* *All namespaces on the cluster*
* *A specific namespace on the cluster*
+
For this example, choose *A specific namespace on the cluster*.

. Select the namespace into which you want to install the Operator, and then click btn:[Install].
+
The *Installed Operators* page appears displaying the status of the Operator installation.

. Verify that the {skupper-name} Operator is displayed and wait until the *Status* changes to *Succeeded*.

. If the installation is not successful, troubleshoot the error:

.. Click `{SkupperOperatorName}` on the *Installed Operators* page.

.. Select the *Subscription* tab and view any failures or errors.

.Additional resources

For more information about installing Operators, see the link:https://docs.openshift.com/container-platform/4.7/operators/user/olm-installing-operators-in-namespace.html[OpenShift Documentation]

