[id='installing-operator-using-cli-{context}']
== Installing the Operator using the CLI

:examples-file: skupper-operator-2.0-ocp-install-examples.zip

The steps in this section show how to use the `kubectl` command-line interface (CLI) to install and deploy the latest version of the {SkupperOperatorName} in a given {kubernetes-flavor} cluster.

.Procedure

// tag::openshift[]

. In your web browser, navigate to the *Software Downloads* page for link:https://access.redhat.com/jbossnetwork/restricted/listSoftware.html?downloadType=distributions&product=jboss.amq.interconnect[{skupper-name} releases].

. Ensure that the value of the *Version* drop-down list is set to `{RouterVersion}` and the *Releases* tab is selected.

. Next to *AMQ Interconnect 2.0 Operator Installation and Example Files*, click *Download*.
+
Download of the `{examples-file}` compressed archive automatically begins.

. When the download has completed, move the archive to your chosen installation directory. The following example moves the archive to a directory called `~/router/operator`.
+
[source,bash,options="nowrap",subs="+attributes"]
----
$ mkdir ~/router
$ mv {examples-file} ~/router
----

. In your chosen installation directory, extract the contents of the archive. For example:
+
[source,bash,options="nowrap", subs="+attributes"]
----
$ cd ~/router
$ unzip {examples-file}
----

. Switch to the directory that was created when you extracted the archive. For example:
+
[source,bash,options="nowrap", subs="+attributes"]
----
$ cd operator
----


. Log in to {kubernetes-flavor} as a cluster administrator. For example:
+
[source,bash,options="nowrap"]
----
$ kubectl login -u system:admin
----


. Complete the steps described in link:https://access.redhat.com/RegistryAuthentication[Red Hat Container Registry Authentication^].

// end::openshift[]


// tag::kubernetes[]



. Download the Skupper Operator example files, for example:
+
----
$ curl -fL https://github.com/skupperproject/skupper-operator/archive/refs/heads/main.zip
----


// end::kubernetes[]



. Specify the namespace in which you want to install the Operator. You can create a new namespace or switch to an existing one.

.. Create a new namespace:
+
[source,bash,options="nowrap",subs="+quotes"]
----
$ kubectl create namespace  __<namespace-name>__
----

.. Or, switch to an existing namespace:
+
[source,bash,options="nowrap",subs="+quotes"]
----
$ kubectl config set-context --current --namespace=__<namespace-name>__
----

. Create a CatalogSource in the `openshift-marketplace` namespace:
+
[source,bash,options="nowrap",subs=attributes+]
----
$ kubectl apply -f examples/{example-directory}/00-cs.yaml
----

. Make sure the skupper-operator catalog pod is running before continuing:
+
[source,bash,options="nowrap",subs=attributes+]
----
$ kubectl -n openshift-marketplace get pods | grep skupper-operator
----

. Create an OperatorGroup in the `my-namespace` namespace:
+
[source,bash,options="nowrap",subs=attributes+]
----
$ kubectl apply -f examples/{example-directory}/10-og.yaml
----

. Create a Subscription  in the `my-namespace` namespace:
+
[source,bash,options="nowrap",subs=attributes+]
----
$ kubectl apply -f examples/{example-directory}/20-sub.yaml
----

. Verify that the Operator is running:
+
[source,bash,options="nowrap"]
----
$ kubectl get pods -n my-namespace

NAME                                     READY   STATUS    RESTARTS   AGE
skupper-site-controller-d7b57964-gxms6   1/1     Running   0          1m
----
+
If the output does not report the pod is running, use the following command to determine the issue that prevented it from running:
+
----
$ kubectl describe pod -l name=skupper-operator
----
