[id='installing-operator-using-cli-{context}']
== Installing the Operator using the CLI

:examples-file: skupper-operator-2.0-ocp-install-examples.zip

The steps in this section show how to use the `kubectl` command-line interface (CLI) to install and deploy the latest version of the {SkupperOperatorName} in a given {kubernetes-flavor} cluster.

.Procedure

. In your web browser, navigate to the *Software Downloads* page for link:https://access.redhat.com/jbossnetwork/restricted/listSoftware.html?downloadType=distributions&product=jboss.amq.interconnect[{skupper-name} releases].

. Ensure that the value of the *Version* drop-down list is set to `{RouterVersion}` and the *Releases* tab is selected.

. Next to *AMQ Interconnect 2.0 Operator Installation and Example Files*, click *Download*.
+
Download of the `{examples-file}` compressed archive automatically begins.

. When the download has completed, move the archive to your chosen installation directory. The following example moves the archive to a directory called `~/router/operator`.
+
[source,bash,options="nowrap",subs="+attributes"]
----
$ mkdir ~/router
$ mv {examples-file} ~/router
----

. In your chosen installation directory, extract the contents of the archive. For example:
+
[source,bash,options="nowrap", subs="+attributes"]
----
$ cd ~/router
$ unzip {examples-file}
----

. Switch to the directory that was created when you extracted the archive. For example:
+
[source,bash,options="nowrap", subs="+attributes"]
----
$ cd operator
----


. Log in to {kubernetes-flavor} as a cluster administrator. For example:
+
[source,bash,options="nowrap"]
----
$ kubectl login -u system:admin
----


. Complete the steps described in link:https://access.redhat.com/RegistryAuthentication[Red Hat Container Registry Authentication^].


:next-step: 9

include::fragment-installing-operator-using-cli.adoc[]